### ISSUE TITLE
Context for sov driver returns a 404 error

### ISSUE THREAD

**Issue by kdenhartog** [decentralized-identity/universal-resolver#106]
Looks like the universal resolver currently returns an invalid context for the sovrin driver in two places. Would it be alright to rip and replace with the current context because it's not resolvable anymore? 

These are the two instances where it's being used: https://github.com/decentralized-identity/universal-resolver/search?q=2019&unscoped_q=2019

This is the link that returns a 404: https://www.w3.org/2019/did/v1

**Comment by colinyip** [comment]
currently, universal resolver is resolving did document for sov with context `https://www.w3.org/2019/did/v1`. Looks like it's coming from [did common java package ](https://github.com/decentralized-identity/did-common-java), particularly [this file](https://github.com/decentralized-identity/did-common-java/blob/master/src/main/resources/did/diddocument-skeleton.jsonld) 

should we be using this context? any plan to update it?

**Comment by peacekeeper** [comment]
@kdenhartog and @colinyip we've deployed some updates in the last few days to be more in line with the current state of DID Core.

Among other things, the correct JSON-LD context should now be returned by the `did:sov`, `did:btcr` and some other drivers.

More work needs to be done, but I think this specific issue here has been addressed. Can we close?

**Comment by kdenhartog** [comment]
Yup, looks good now. Looks to be updated here: https://github.com/decentralized-identity/did-common-java/blob/master/src/main/java/foundation/identity/did/jsonld/DIDContexts.java

Thanks @peacekeeper
