### ISSUE TITLE
Cannot resolve decentralized-identity:did-common-java:0.1.0

### ISSUE THREAD

**Issue by Primordium** [decentralized-identity/universal-resolver#107]
Hi, I'm getting this error during initial setup,
I assume it's all about the github token and username, could you please clarify how to properly setup those?
I already have a token, that because lack of knowledge I hard pasted in settings.xml, also the username.

**Comment by cihanss** [comment]
> I hard pasted in settings.xml

If you did it in the correct [settings.xml file](https://github.com/decentralized-identity/universal-resolver/blob/master/resolver/java/settings.xml), your approach should work. You need to **replace the entire field** with your token parameters, such as: 

```
<username>${env.GITHUB_READ_PACKAGES_OWNER}</username> -> <username>your_user_name</username>
<password>${env.GITHUB_READ_PACKAGES_TOKEN}</password> -> <password>your_access_token</password>
```

Another option is passing the information as **build arguments**. For example, if you want to build **uni-resolver-client**, and assuming you are calling the build from your [universal-resolver/resolver/java/uni-resolver-client path](https://github.com/decentralized-identity/universal-resolver/tree/master/resolver/java/uni-resolver-client)


`docker build --build-arg GITHUB_READ_PACKAGES_OWNER=<your_user_name> --build-arg GITHUB_READ_PACKAGES_TOKEN=<your_access_token> -f docker/Dockerfile -t <your_image_tag>  ../../../` will do the job. 

You can also include **environment variables in the Dockerfile**, such as:

```
ENV GITHUB_READ_PACKAGES_OWNER=<your_user_name>
ENV GITHUB_READ_PACKAGES_TOKEN=<your_access_token>
```

**Comment by Primordium** [comment]
I think the problem lies elsewhere. I clone and built did-common-java and right now, the version is at 0.2-SNAPSHOT. Maybe that's why it's failing

**Comment by cihanss** [comment]
Removed in-docker builds of the did-common-java to prevent confusion. did-common-java:0.1.0 is the dependency defined in uni-resolver-core, and in-docker build of it should have been removed since components have the dependency on the uni-resolver-core, and maven dependencies are transitive.
