### ISSUE TITLE
Unable to resolve driver

### ISSUE THREAD

**Issue by thomas-tran** [decentralized-identity/universal-resolver#109]
I tried to add the driver to the repository and test locally. However, the universal resolver  did not add my driver during the initialized
Below are a fork and log file
https://github.com/thomas-tran/universal-resolver

Log file
DEBUG [uniresolver.local.LocalUniResolver] - Identifier did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK is a valid DID URL: did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK

11:44:05,683 - DEBUG [uniresolver.local.LocalUniResolver] - Identifier did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK is a valid DID URL: did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK

11:44:05,684 - DEBUG [uniresolver.local.LocalUniResolver] - Resolving identifier: did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK

11:44:05,684 - DEBUG [uniresolver.local.LocalUniResolver] - Resolving identifier: did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK

11:44:05,684 - DEBUG [uniresolver.local.LocalUniResolver] - Attemping to resolve did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK with driver class uniresolver.driver.http.HttpDriver

11:44:05,684 - DEBUG [uniresolver.local.LocalUniResolver] - Attemping to resolve did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK with driver class uniresolver.driver.http.HttpDriver

11:44:05,685 - DEBUG [uniresolver.driver.http.HttpDriver] - Skipping identifier did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK - does not match pattern ^(did:abt:.+)$

11:44:05,685 - DEBUG [uniresolver.driver.http.HttpDriver] - Skipping identifier did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK - does not match pattern ^(did:abt:.+)$

11:44:05,685 - DEBUG [uniresolver.local.LocalUniResolver] - Attemping to resolve did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK with driver class uniresolver.driver.http.HttpDriver

11:44:05,685 - DEBUG [uniresolver.local.LocalUniResolver] - Attemping to resolve did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK with driver class uniresolver.driver.http.HttpDriver

11:44:05,686 - DEBUG [uniresolver.driver.http.HttpDriver] - Skipping identifier did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK - does not match pattern ^((?:(?:[a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])\.)*(?:[A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]*[A-Za-z0-9]))$

11:44:05,686 - DEBUG [uniresolver.driver.http.HttpDriver] - Skipping identifier did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK - does not match pattern ^((?:(?:[a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])\.)*(?:[A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]*[A-Za-z0-9]))$

11:44:05,687 - DEBUG [uniresolver.local.LocalUniResolver] - Attemping to resolve did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK with driver class uniresolver.driver.http.HttpDriver

11:44:05,687 - DEBUG [uniresolver.local.LocalUniResolver] - Attemping to resolve did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK with driver class uniresolver.driver.http.HttpDriver

11:44:05,687 - DEBUG [uniresolver.driver.http.HttpDriver] - Skipping identifier did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK - does not match pattern ^(did:evan:.+)$

11:44:05,687 - DEBUG [uniresolver.driver.http.HttpDriver] - Skipping identifier did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK - does not match pattern ^(did:evan:.+)$

11:44:05,688 - DEBUG [uniresolver.local.LocalUniResolver] - Attemping to resolve did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK with driver class uniresolver.driver.http.HttpDriver

11:44:05,688 - DEBUG [uniresolver.local.LocalUniResolver] - Attemping to resolve did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK with driver class uniresolver.driver.http.HttpDriver

11:44:05,689 - DEBUG [uniresolver.driver.http.HttpDriver] - Skipping identifier did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK - does not match pattern ^(did:trustbloc:.+)$

11:44:05,689 - DEBUG [uniresolver.driver.http.HttpDriver] - Skipping identifier did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK - does not match pattern ^(did:trustbloc:.+)$

11:44:05,689 - DEBUG [uniresolver.local.LocalUniResolver] - Attemping to resolve did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK with driver class uniresolver.driver.http.HttpDriver

11:44:05,689 - DEBUG [uniresolver.local.LocalUniResolver] - Attemping to resolve did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK with driver class uniresolver.driver.http.HttpDriver

11:44:05,690 - DEBUG [uniresolver.driver.http.HttpDriver] - Skipping identifier did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK - does not match pattern ^did:ipid:(.+)$

11:44:05,690 - DEBUG [uniresolver.driver.http.HttpDriver] - Skipping identifier did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK - does not match pattern ^did:ipid:(.+)$

11:44:05,690 - DEBUG [uniresolver.local.LocalUniResolver] - Attemping to resolve did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK with driver class uniresolver.driver.http.HttpDriver

11:44:05,690 - DEBUG [uniresolver.local.LocalUniResolver] - Attemping to resolve did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK with driver class uniresolver.driver.http.HttpDriver

11:44:05,691 - DEBUG [uniresolver.driver.http.HttpDriver] - Skipping identifier did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK - does not match pattern ^(did:neoid:.+)$

11:44:05,691 - DEBUG [uniresolver.driver.http.HttpDriver] - Skipping identifier did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK - does not match pattern ^(did:neoid:.+)$

11:44:05,696 - DEBUG [uniresolver.local.LocalUniResolver] - Attemping to resolve did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK with driver class uniresolver.driver.http.HttpDriver

11:44:05,696 - DEBUG [uniresolver.local.LocalUniResolver] - Attemping to resolve did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK with driver class uniresolver.driver.http.HttpDriver

11:44:05,697 - DEBUG [uniresolver.driver.http.HttpDriver] - Skipping identifier did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK - does not match pattern ^(did:ont:.+)$

11:44:05,697 - DEBUG [uniresolver.driver.http.HttpDriver] - Skipping identifier did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK - does not match pattern ^(did:ont:.+)$

11:44:05,698 - DEBUG [uniresolver.local.LocalUniResolver] - Attemping to resolve did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK with driver class uniresolver.driver.http.HttpDriver

11:44:05,698 - DEBUG [uniresolver.local.LocalUniResolver] - Attemping to resolve did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK with driver class uniresolver.driver.http.HttpDriver

11:44:05,698 - DEBUG [uniresolver.driver.http.HttpDriver] - Skipping identifier did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK - does not match pattern ^(did:sov:(?:(?:\w[-\w]*(?::\w[-\w]*)*):)?(?:[1-9A-HJ-NP-Za-km-z]{21,22}))$

11:44:05,698 - DEBUG [uniresolver.driver.http.HttpDriver] - Skipping identifier did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK - does not match pattern ^(did:sov:(?:(?:\w[-\w]*(?::\w[-\w]*)*):)?(?:[1-9A-HJ-NP-Za-km-z]{21,22}))$

11:44:05,699 - DEBUG [uniresolver.local.LocalUniResolver] - Attemping to resolve did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK with driver class uniresolver.driver.http.HttpDriver

11:44:05,699 - DEBUG [uniresolver.local.LocalUniResolver] - Attemping to resolve did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK with driver class uniresolver.driver.http.HttpDriver

11:44:05,700 - DEBUG [uniresolver.driver.http.HttpDriver] - Skipping identifier did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK - does not match pattern ^(did:nacl:.+)$

11:44:05,700 - DEBUG [uniresolver.driver.http.HttpDriver] - Skipping identifier did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK - does not match pattern ^(did:nacl:.+)$

11:44:05,700 - DEBUG [uniresolver.local.LocalUniResolver] - Attemping to resolve did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK with driver class uniresolver.driver.http.HttpDriver

11:44:05,700 - DEBUG [uniresolver.local.LocalUniResolver] - Attemping to resolve did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK with driver class uniresolver.driver.http.HttpDriver

11:44:05,701 - DEBUG [uniresolver.driver.http.HttpDriver] - Skipping identifier did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK - does not match pattern ^(did:key:.+)$

11:44:05,701 - DEBUG [uniresolver.driver.http.HttpDriver] - Skipping identifier did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK - does not match pattern ^(did:key:.+)$

11:44:05,702 - DEBUG [uniresolver.local.LocalUniResolver] - Attemping to resolve did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK with driver class uniresolver.driver.http.HttpDriver

11:44:05,702 - DEBUG [uniresolver.local.LocalUniResolver] - Attemping to resolve did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK with driver class uniresolver.driver.http.HttpDriver

11:44:05,703 - DEBUG [uniresolver.driver.http.HttpDriver] - Skipping identifier did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK - does not match pattern ^(did:stack:.+)$

11:44:05,703 - DEBUG [uniresolver.driver.http.HttpDriver] - Skipping identifier did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK - does not match pattern ^(did:stack:.+)$

11:44:05,704 - DEBUG [uniresolver.local.LocalUniResolver] - Attemping to resolve did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK with driver class uniresolver.driver.http.HttpDriver

11:44:05,704 - DEBUG [uniresolver.local.LocalUniResolver] - Attemping to resolve did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK with driver class uniresolver.driver.http.HttpDriver

11:44:05,705 - DEBUG [uniresolver.driver.http.HttpDriver] - Skipping identifier did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK - does not match pattern ^(did:echo:.+)$

11:44:05,705 - DEBUG [uniresolver.driver.http.HttpDriver] - Skipping identifier did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK - does not match pattern ^(did:echo:.+)$

11:44:05,705 - DEBUG [uniresolver.local.LocalUniResolver] - Attemping to resolve did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK with driver class uniresolver.driver.http.HttpDriver

11:44:05,705 - DEBUG [uniresolver.local.LocalUniResolver] - Attemping to resolve did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK with driver class uniresolver.driver.http.HttpDriver

11:44:05,706 - DEBUG [uniresolver.driver.http.HttpDriver] - Skipping identifier did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK - does not match pattern ^(did:v1:nym:.+)$

11:44:05,706 - DEBUG [uniresolver.driver.http.HttpDriver] - Skipping identifier did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK - does not match pattern ^(did:v1:nym:.+)$

11:44:05,707 - DEBUG [uniresolver.local.LocalUniResolver] - Attemping to resolve did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK with driver class uniresolver.driver.http.HttpDriver

11:44:05,707 - DEBUG [uniresolver.local.LocalUniResolver] - Attemping to resolve did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK with driver class uniresolver.driver.http.HttpDriver

11:44:05,707 - DEBUG [uniresolver.driver.http.HttpDriver] - Skipping identifier did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK - does not match pattern ^(did:github:.+)$

11:44:05,707 - DEBUG [uniresolver.driver.http.HttpDriver] - Skipping identifier did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK - does not match pattern ^(did:github:.+)$

11:44:05,709 - DEBUG [uniresolver.local.LocalUniResolver] - Attemping to resolve did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK with driver class uniresolver.driver.http.HttpDriver

11:44:05,709 - DEBUG [uniresolver.local.LocalUniResolver] - Attemping to resolve did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK with driver class uniresolver.driver.http.HttpDriver

11:44:05,711 - DEBUG [uniresolver.driver.http.HttpDriver] - Skipping identifier did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK - does not match pattern ^did:elem:(.+)$

11:44:05,711 - DEBUG [uniresolver.driver.http.HttpDriver] - Skipping identifier did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK - does not match pattern ^did:elem:(.+)$

11:44:05,712 - DEBUG [uniresolver.local.LocalUniResolver] - Attemping to resolve did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK with driver class uniresolver.driver.http.HttpDriver

11:44:05,712 - DEBUG [uniresolver.local.LocalUniResolver] - Attemping to resolve did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK with driver class uniresolver.driver.http.HttpDriver

11:44:05,713 - DEBUG [uniresolver.driver.http.HttpDriver] - Skipping identifier did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK - does not match pattern ^(did:jolo:.+)$

11:44:05,713 - DEBUG [uniresolver.driver.http.HttpDriver] - Skipping identifier did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK - does not match pattern ^(did:jolo:.+)$

11:44:05,714 - DEBUG [uniresolver.local.LocalUniResolver] - Attemping to resolve did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK with driver class uniresolver.driver.http.HttpDriver

11:44:05,714 - DEBUG [uniresolver.local.LocalUniResolver] - Attemping to resolve did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK with driver class uniresolver.driver.http.HttpDriver

11:44:05,714 - DEBUG [uniresolver.driver.http.HttpDriver] - Skipping identifier did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK - does not match pattern ^(did:erc725:.+)$

11:44:05,714 - DEBUG [uniresolver.driver.http.HttpDriver] - Skipping identifier did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK - does not match pattern ^(did:erc725:.+)$

11:44:05,715 - DEBUG [uniresolver.local.LocalUniResolver] - Attemping to resolve did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK with driver class uniresolver.driver.http.HttpDriver

11:44:05,715 - DEBUG [uniresolver.local.LocalUniResolver] - Attemping to resolve did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK with driver class uniresolver.driver.http.HttpDriver

11:44:05,716 - DEBUG [uniresolver.driver.http.HttpDriver] - Skipping identifier did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK - does not match pattern ^(did:v1:test:nym:.+)$

11:44:05,716 - DEBUG [uniresolver.driver.http.HttpDriver] - Skipping identifier did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK - does not match pattern ^(did:v1:test:nym:.+)$

11:44:05,717 - DEBUG [uniresolver.local.LocalUniResolver] - Attemping to resolve did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK with driver class uniresolver.driver.http.HttpDriver

11:44:05,717 - DEBUG [uniresolver.local.LocalUniResolver] - Attemping to resolve did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK with driver class uniresolver.driver.http.HttpDriver

11:44:05,718 - DEBUG [uniresolver.driver.http.HttpDriver] - Skipping identifier did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK - does not match pattern ^(did:web:.+)$

11:44:05,718 - DEBUG [uniresolver.driver.http.HttpDriver] - Skipping identifier did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK - does not match pattern ^(did:web:.+)$

11:44:05,718 - DEBUG [uniresolver.local.LocalUniResolver] - Attemping to resolve did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK with driver class uniresolver.driver.http.HttpDriver

11:44:05,718 - DEBUG [uniresolver.local.LocalUniResolver] - Attemping to resolve did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK with driver class uniresolver.driver.http.HttpDriver

11:44:05,719 - DEBUG [uniresolver.driver.http.HttpDriver] - Skipping identifier did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK - does not match pattern ^(did:btcr:.+)$

11:44:05,719 - DEBUG [uniresolver.driver.http.HttpDriver] - Skipping identifier did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK - does not match pattern ^(did:btcr:.+)$

11:44:05,720 - DEBUG [uniresolver.local.LocalUniResolver] - Attemping to resolve did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK with driver class uniresolver.driver.http.HttpDriver

11:44:05,720 - DEBUG [uniresolver.local.LocalUniResolver] - Attemping to resolve did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK with driver class uniresolver.driver.http.HttpDriver

11:44:05,721 - DEBUG [uniresolver.driver.http.HttpDriver] - Skipping identifier did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK - does not match pattern ^(did:ethr:.+)$

11:44:05,721 - DEBUG [uniresolver.driver.http.HttpDriver] - Skipping identifier did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK - does not match pattern ^(did:ethr:.+)$

11:44:05,721 - DEBUG [uniresolver.local.LocalUniResolver] - Attemping to resolve did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK with driver class uniresolver.driver.http.HttpDriver

11:44:05,721 - DEBUG [uniresolver.local.LocalUniResolver] - Attemping to resolve did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK with driver class uniresolver.driver.http.HttpDriver

11:44:05,722 - DEBUG [uniresolver.driver.http.HttpDriver] - Skipping identifier did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK - does not match pattern ^(did:work:.+)$

11:44:05,722 - DEBUG [uniresolver.driver.http.HttpDriver] - Skipping identifier did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK - does not match pattern ^(did:work:.+)$

11:44:05,723 - DEBUG [uniresolver.local.LocalUniResolver] - Attemping to resolve did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK with driver class uniresolver.driver.http.HttpDriver

11:44:05,723 - DEBUG [uniresolver.local.LocalUniResolver] - Attemping to resolve did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK with driver class uniresolver.driver.http.HttpDriver

11:44:05,723 - DEBUG [uniresolver.driver.http.HttpDriver] - Skipping identifier did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK - does not match pattern ^(did:kilt:.+)$

11:44:05,723 - DEBUG [uniresolver.driver.http.HttpDriver] - Skipping identifier did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK - does not match pattern ^(did:kilt:.+)$

11:44:05,724 - DEBUG [uniresolver.local.LocalUniResolver] - Attemping to resolve did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK with driver class uniresolver.driver.http.HttpDriver

11:44:05,724 - DEBUG [uniresolver.local.LocalUniResolver] - Attemping to resolve did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK with driver class uniresolver.driver.http.HttpDriver

11:44:05,725 - DEBUG [uniresolver.driver.http.HttpDriver] - Skipping identifier did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK - does not match pattern ^(did:dock:[a-zA-Z0-9]+)$

11:44:05,725 - DEBUG [uniresolver.driver.http.HttpDriver] - Skipping identifier did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK - does not match pattern ^(did:dock:[a-zA-Z0-9]+)$

11:44:05,726 - DEBUG [uniresolver.local.LocalUniResolver] - Attemping to resolve did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK with driver class uniresolver.driver.http.HttpDriver

11:44:05,726 - DEBUG [uniresolver.local.LocalUniResolver] - Attemping to resolve did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK with driver class uniresolver.driver.http.HttpDriver

11:44:05,727 - DEBUG [uniresolver.driver.http.HttpDriver] - Skipping identifier did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK - does not match pattern ^(did:hcr:.+)$

11:44:05,727 - DEBUG [uniresolver.driver.http.HttpDriver] - Skipping identifier did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK - does not match pattern ^(did:hcr:.+)$

11:44:05,728 - DEBUG [uniresolver.local.LocalUniResolver] - Attemping to resolve did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK with driver class uniresolver.driver.http.HttpDriver

11:44:05,728 - DEBUG [uniresolver.local.LocalUniResolver] - Attemping to resolve did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK with driver class uniresolver.driver.http.HttpDriver

11:44:05,729 - DEBUG [uniresolver.driver.http.HttpDriver] - Skipping identifier did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK - does not match pattern ^(did:ccp:.+)$

11:44:05,729 - DEBUG [uniresolver.driver.http.HttpDriver] - Skipping identifier did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK - does not match pattern ^(did:ccp:.+)$

11:44:05,729 - DEBUG [uniresolver.local.LocalUniResolver] - Attemping to resolve did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK with driver class uniresolver.driver.http.HttpDriver

11:44:05,729 - DEBUG [uniresolver.local.LocalUniResolver] - Attemping to resolve did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK with driver class uniresolver.driver.http.HttpDriver

11:44:05,730 - DEBUG [uniresolver.driver.http.HttpDriver] - Skipping identifier did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK - does not match pattern ^(did:factom:.+)$

11:44:05,730 - DEBUG [uniresolver.driver.http.HttpDriver] - Skipping identifier did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK - does not match pattern ^(did:factom:.+)$

11:44:05,731 - DEBUG [uniresolver.local.LocalUniResolver] - No result with 27 drivers.

11:44:05,731 - DEBUG [uniresolver.local.LocalUniResolver] - No result with 27 drivers.

11:44:05,765 - INFO [uniresolver.web.WebUniResolver] - Resolve result for did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK: {"didDocument":null,"content":null,"contentType":null,"resolverMetadata":{"duration":121,"identifier":"did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK","didUrl":{"didUrlString":"did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK","did":{"didString":"did:sirius:2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK","method":"sirius","methodSpecificId":"2VhYrbauc2cCx9ZpCp5wrDtK7HKf7jrsvgoKBD4KgK","parseTree":null,"parseRuleCount":null},"parameters":null,"parametersMap":{},"path":"","query":null,"fragment":null,"parseTree":null,"parseRuleCount":null}},"methodMetadata":{}}

**Comment by yutongp** [comment]
hi @thomas-tran, did you able to resolve this issue? I think we are having the same issue here.

**Comment by yutongp** [comment]
I figured out.

**Comment by thomas-tran** [comment]
No, I haven't resolved this yet, can you share the solution?

**Comment by thomas-tran** [comment]
Fixed and closed this issue
