### ISSUE TITLE
universal-resolver build is failing

### ISSUE THREAD

**Issue by bjwswang** [decentralized-identity/universal-resolver#111]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  12.996 s
[INFO] Finished at: 2020-06-24T11:40:33Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project uni-resolver-core: Could not resolve dependencies for project decentralized-identity:uni-resolver-core:jar:0.2-SNAPSHOT: Failed to collect dependencies at decentralized-identity:did-common-java:jar:0.1.0: Failed to read artifact descriptor for decentralized-identity:did-common-java:jar:0.1.0: Could not transfer artifact decentralized-identity:did-common-java:pom:0.1.0 from/to github-did-common-java (https://maven.pkg.github.com/decentralized-identity/did-common-java): Transfer failed for https://maven.pkg.github.com/decentralized-identity/did-common-java/decentralized-identity/did-common-java/0.1.0/did-common-java-0.1.0.pom 400 Bad Request -> [Help 1]

**Comment by yutongp** [comment]
+1. having the same issue here

**Comment by thomas-tran** [comment]
You need to register the personal token in order to download the did-common-java as it is in the private maven package.

**Comment by yutongp** [comment]
@thomas-tran Thanks for the explanation, with the GitHub token now I can build the docker locally. But we still having this issue on the githhub CI. Any suggestion how pass the CI?
<img width="1077" alt="Screen Shot 2020-06-26 at 10 11 37 AM" src="https://user-images.githubusercontent.com/915849/85884454-91115b80-b797-11ea-9a22-b31581f6ee61.png">

**Comment by BernhardFuchs** [comment]
#114

**Comment by peacekeeper** [comment]
@bjwswang and @yutongp we have now changed the build process to use a public Maven repository that doesn't require any tokens or other authentication. This should make everything much easier and more stable. See commit https://github.com/decentralized-identity/universal-resolver/commit/cbec02d1039d6df2e55b23879ebeca5dd3ec3e4f for details. If you agree this fixes the problem, can we close this issue?

**Comment by bjwswang** [comment]
@peacekeeper  sorry for being so late to response. we are good. I will close this issue right now. Thank you! BTW..  what's the plan on pr review?
