### ISSUE TITLE
CI failed on download the did-common-java 

### ISSUE THREAD

**Issue by yutongp** [decentralized-identity/universal-resolver#114]
<img width="1077" alt="Screen Shot 2020-06-26 at 10 11 37 AM" src="https://user-images.githubusercontent.com/915849/85904356-5cb09600-b7bd-11ea-948d-873e4a5ae374.png">

I understand to download this private maven package, I need to set github token locally, but I am not sure how to handle this issue in CI.
Any suggestion? Thank you!

**Comment by BernhardFuchs** [comment]
Builds for Pull Requests are not working at the moment. We are working on a solution without using the github packages at all.

Till then it is possible to run the CI pipeline in a forked repository with following steps:

1. Create a base64 encoded string of the settings.xml file (or the maven settings file which includes the github token)
2. In the forked repo go to Settings -> Secrets and add the secret MAVEN_SETTINGS with the encoded string from step 1
3. Go to Actions, activate them and trigger it by pushing a change to master

**Comment by peacekeeper** [comment]
@yutongp we have now changed the build process to use a public Maven repository that doesn't require any tokens or other authentication. This should make everything much easier and more stable. See commit https://github.com/decentralized-identity/universal-resolver/commit/cbec02d1039d6df2e55b23879ebeca5dd3ec3e4f for details. If you agree this fixes the problem, can we close this issue?

**Comment by yutongp** [comment]
> @yutongp we have now changed the build process to use a public Maven repository that doesn't require any tokens or other authentication. This should make everything much easier and more stable. See commit [cbec02d](https://github.com/decentralized-identity/universal-resolver/commit/cbec02d1039d6df2e55b23879ebeca5dd3ec3e4f) for details. If you agree this fixes the problem, can we close this issue?

that is great. thank you for fixing it!
