### ISSUE TITLE
Unable to resolve driver-did-mpg

### ISSUE THREAD

**Issue by mpgshankar** [decentralized-identity/universal-resolver#129]
Resolve problem for did:mpg:7PGGnRdvKKFftSXU3Jw75Vk5npfg: Cannot retrieve RESOLVE RESULT for did:mpg:7PGGnRdvKKFftSXU3Jw75Vk5npfg from http://driver-did-mpg:8080/1.0/identifiers/did:mpg:7PGGnRdvKKFftSXU3Jw75Vk5npfg: driver-did-mpg: Name or service not known

**Comment by BernhardFuchs** [comment]
Seems to work again.
