### ISSUE TITLE
DIDs must return JSON arrays instead of JSON object

### ISSUE THREAD

**Issue by ricjcosme** [decentralized-identity/universal-resolver#14]
The universal resolver implementation needs to be corrected and updated to reflect the current draft standards definition for the authentication and service properties:

- "The value of the authentication property should be an array of proof mechanisms." ([4.4 point 2](https://w3c-ccg.github.io/did-spec/#authentication))
- "The value of the service property should be an array of service endpoints." ([4.6 point 2](https://w3c-ccg.github.io/did-spec/#service-endpoints))

Calling the UR with `curl http://localhost:8080/1.0/identifiers/did:sov:WRfXPg8dantKVubE3HX8pw` returns the following didDocument:

```
{
	"id": "did:sov:WRfXPg8dantKVubE3HX8pw",
	"service": {
		"type": "xdi",
		"serviceEndpoint": "http://127.0.0.1:8080/xdi"
	},
	"authentication": {
		"type": "Ed25519SignatureAuthentication2018",
		"publicKey": ["did:sov:WRfXPg8dantKVubE3HX8pw#key-1"]
	},
	"publicKey": [{
		"id": "did:sov:WRfXPg8dantKVubE3HX8pw#key-1",
		"type": "Ed25519VerificationKey2018",
		"publicKeyBase58": "H3C2AVvLMv6gmMNam3uVAjZpfkcJCwDwnZn6z3wXmqPV"
	}],
	"@context": "https://w3id-temp.org/did/v1"
}
```
where authentication and service are a JSON object and not a JSON array.

This causes an unecessary verification overhead for people currently using the UR.

**Comment by peacekeeper** [comment]
Thanks for pointing this out. You are right that the UR (or its drivers) may currently return a JSON object rather than array in cases when there's only a single "service" or "authentication" or "publicKey".

I guess the spec isn't very clear when it says "should".

From a JSON-LD standpoint, I believe both is valid. I can understand why always using arrays would be preferable.

**Comment by azuzi** [comment]
This issue is solved in the new current version of UR.
