### ISSUE TITLE
Certificate expired on https://uniresolver.io/

### ISSUE THREAD

**Issue by nklomp** [decentralized-identity/universal-resolver#143]
Not sure whether this is the correct location for this infra bug report, but wanted to let you know that the Letsencrypt certificate for 
https://uniresolver.io/ has expired yesterday on September 13th 2020

![image](https://user-images.githubusercontent.com/13615304/93088941-e1af9b00-f69a-11ea-88ee-62fb1043bb13.png)

**Comment by peacekeeper** [comment]
Thanks for the report, just renewed the certificate!
