### ISSUE TITLE
Value in JsonObjects name/value pair cannot be null

### ISSUE THREAD

**Issue by gjgd** [decentralized-identity/universal-resolver#152]
When resolving any identifier on https://dev.uniresolver.io/ I get the following error:

`Error: Request failed with status code 500: Resolve problem for did:elem:EiAS3mqC4OLMKOwcz3ItIL7XfWduPT7q3Fa4vHgiCfSG2A: Value in JsonObjects name/value pair cannot be null`
<img width="1906" alt="Screenshot 2020-10-14 at 12 58 39" src="https://user-images.githubusercontent.com/7913565/95980125-fd829a00-0e1c-11eb-86d2-9c811ad7c208.png">

**Comment by OR13** [comment]
Is this because the sidetree resolver is returning null values?

**Comment by gjgd** [comment]
The error mentioned in the title isn't happening anymore, though now a different one crashes the page when resolving any identifier: `TypeError: this.props.resolverMetadata is undefined`

**Comment by gjgd** [comment]
The error is not specific to sidetree based did methods

**Comment by peacekeeper** [comment]
Sorry it's an internal bug following an update today.. We're working on fixing it.

**Comment by peacekeeper** [comment]
This error should be fixed now. We're still working on a few other improvements.

**Comment by OR13** [comment]
thanks!

**Comment by gjgd** [comment]
Closing this since Im not seeing the error anymore. Thanks!
