### ISSUE TITLE
ghcr.io should be allowed

### ISSUE THREAD

**Issue by troyronda** [decentralized-identity/universal-resolver#167]
The GitHub container registry (ghcr.io) allows for anonymous pulls/reads.

Please consider allowing us to use our driver images that are hosted on `ghcr.io`, rather than requiring us to mirror driver images into dockerhub.

**Comment by peacekeeper** [comment]
Good idea! @BernhardFuchs and I discussed this today, and we agreed we'll work on supporting this.
