### ISSUE TITLE
Update did web driver to support pathname based dids

### ISSUE THREAD

**Issue by OR13** [decentralized-identity/universal-resolver#168]
See: https://github.com/w3c-ccg/did-method-web/issues/24

We should be able to resolver pathname based did webs, with the universal resolver

**Comment by mirceanis** [comment]
@OR13 this already works for a few months. see `did:web:did.actor:alice`

What doesn't work (but I'm fixing this now) is `did:web:did.actor:mike` which uses `verificationMethod` instead of `publicKey`
