### ISSUE TITLE
The Stable Version Server is Down

### ISSUE THREAD

**Issue by Muhammad-Altabba** [decentralized-identity/universal-resolver#170]
Hello,
The website https://resolver.identity.foundation/ is down.
I tried it a couple of times yesterday and today.

![image](https://user-images.githubusercontent.com/24407834/109044193-671b8a80-76d2-11eb-91b7-dfae532126ed.png)

**Comment by BernhardFuchs** [comment]
Seems to be back again.  
If you encounter issues with https://resolver.identity.foundation/ there is https://dev.uniresolver.io/ for a fallback.

**Comment by peacekeeper** [comment]
Just as a quick additional note, https://resolver.identity.foundation/ is NOT a production service, so things like that are expected to happen from time to time. But thanks a lot for reporting! We will see if we can improve stability in the future.

**Comment by Muhammad-Altabba** [comment]
Thanks @peacekeeper for highlighting this. Because the readme file refers to this service (https://resolver.identity.foundation/) as `a stable version`. 

And so, I have a question: what is the recommended way to have and to connect to a production service? Do you recommend that every project that needs the DID Universal Resolver to run this repository with all its docker containers on the company premises or on its own cloud servers? Or is there another preferred way?
