### ISSUE TITLE
Missing Docker Image for seraph-id-did-driver

### ISSUE THREAD

**Issue by solidnerd** [decentralized-identity/universal-resolver#181]
Hey, 
during a nightly build, we found that [SeraphID](https://github.com/swisscom-blockchain/seraph-id-did-driver) docker image is missing now on Docker Hub.

When you follow the link: https://hub.docker.com/r/swisscomblockchainag/seraph-id-did-driver it returns a 404.

**Comment by BernhardFuchs** [comment]
We don't have any control over the dockerhub account of swisscomblockchainag.  
The driver repo is at https://github.com/swisscom-blockchain/seraph-id-did-driver  
Maybe @tsmcalister or @milonite can help.

**Comment by tsmcalister** [comment]
I don't work for the company anymore, and I also can't act on their behalf.
My feeling is that this project is no longer active and that the driver can be removed.
I would suggest contacting them through [blockchain@swisscom.com](mailto:blockchain@swisscom.com).

**Comment by securekim** [comment]
Please remove that driver in yml. I can't start docker with seraph.
ERROR: pull access denied for swisscomblockchainag/seraph-id-did-driver, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
