### ISSUE TITLE
"Java components" link broken in README

### ISSUE THREAD

**Issue by CluEleSsUK** [decentralized-identity/universal-resolver#185]
Currently it points to `https://github.com/decentralized-identity/universal-resolver/blob/main/resolver/java`.  
Ought it point to `https://github.com/decentralized-identity/universal-resolver/tree/main/uni-resolver-client` instead?

**Comment by peacekeeper** [comment]
Thanks for finding this! The link should lead to https://github.com/decentralized-identity/universal-resolver/blob/main/docs/java-components.md.

Should be fixed now.
