### ISSUE TITLE
Driver did:trust still active?

### ISSUE THREAD

**Issue by peacekeeper** [decentralized-identity/universal-resolver#186]
The driver for `did:trust` was added in https://github.com/decentralized-identity/universal-resolver/pull/124, but it doesn't seem to be working.

@bjwswang is this DID method still active? It's not listed in https://w3c.github.io/did-spec-registries/#did-methods either.

**Comment by cre8** [comment]
@bjwswang we would like to use the method method name for our own network since it is based on the `trustchain` technolgie.

**Comment by bjwswang** [comment]
@peacekeeper  we are stilling using this method name. Let me check with our engineers. I believe that is a upgrade issue. 

@cre8 I am not quite understand...  but I am sure we still need this method name for now.

**Comment by cre8** [comment]
@bjwswang if you are still using the method name I am fine with it. But if not I would be happy to replace yours with our resolver.

**Comment by BernhardFuchs** [comment]
The driver got an update and is working again.
