### ISSUE TITLE
Some features missing

### ISSUE THREAD

**Issue by remyahalza** [decentralized-identity/universal-resolver#193]
I clone this repository and worked
i got like
![image](https://user-images.githubusercontent.com/68893691/115505427-837b1400-a28a-11eb-9c6c-309dd2cba686.png)
i need to get the front end like this,

![image](https://user-images.githubusercontent.com/68893691/115505466-9261c680-a28a-11eb-9c15-185f074ac444.png)

Is it posible?

**Comment by BernhardFuchs** [comment]
Thanks for trying out our application, it seems the backend is running just fine.  
The missing piece in your setup is the [frontend application](https://github.com/decentralized-identity/universal-resolver-frontend). Guess we could improve our messaging on the standard backend response.

**Comment by peacekeeper** [comment]
We discussed this in the [29 Sep 2021 Universal Resolver work item call](https://github.com/decentralized-identity/identifiers-discovery/blob/main/agenda.md#special-work-item-calls), and created PR https://github.com/decentralized-identity/universal-resolver/pull/244 to add a note that the frontend has to be installed separately.

@remyahalza we think this should be addressed and are therefore closing the issue. Feel free to re-open if you still have questions about this.
