### ISSUE TITLE
frontend and backend

### ISSUE THREAD

**Issue by remyagrai** [decentralized-identity/universal-resolver#194]
how to connect universal resolver front end and backend?

**Comment by BernhardFuchs** [comment]
Sorry for the late reply. Probably the easiest way to run a local instance of the Resolver, is to use `docker-compose` for the backend and run the [frontend](https://github.com/decentralized-identity/universal-resolver-frontend) as a local dev server with `npm run dev`, which will be served at port `7081`.  

Another option is to run the frontend as [docker-container](https://github.com/decentralized-identity/universal-resolver-frontend).

**Comment by peacekeeper** [comment]
We discussed this on the [29 Sep 2021 Universal Resolver work item call](https://github.com/decentralized-identity/identifiers-discovery/blob/main/agenda.md#special-work-item-calls). This is related to https://github.com/decentralized-identity/universal-resolver/issues/193 which we addressed in a PR. We think your question with regard to the frontend was answered by @BernhardFuchs 

We're therefore closing this issue, but feel free to re-open if you still have questions.
