### ISSUE TITLE
Add example identifiers which resolve successfully

### ISSUE THREAD

**Issue by jsanders** [decentralized-identity/universal-resolver#22]
When I follow the instructions in the [blog post](https://medium.com/decentralized-identity/a-universal-resolver-for-self-sovereign-identifiers-48e6b4a5cc3c), I get 403 errors for all the example identifiers. It would be nice to see successful responses to get a sense for what to expect.

For example:

```
$ curl -v -X GET http://localhost:8080/1.0/identifiers/did:sov:WRfXPg8dantKVubE3HX8pw
Note: Unnecessary use of -X or --request, GET is already inferred.
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8080 (#0)
> GET /1.0/identifiers/did:sov:WRfXPg8dantKVubE3HX8pw HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 403 Forbidden
* no chunk, no close, no size. Assume close to signal end
<
* Closing connection 0
```

**Comment by azuzi** [comment]
@jsanders ,

Thanks for your report. You can follow the newly updated README.md from here : https://github.com/decentralized-identity/universal-resolver .
