### ISSUE TITLE
Update spec/explainer to specify the correct Resolver return object

### ISSUE THREAD

**Issue by csuwildcat** [decentralized-identity/universal-resolver#23]
The return object in the spec/explainer appears out of date, is there somewhere with the current, updated spec that I can use to update the text in this repo?

**Comment by peacekeeper** [comment]
Right now, the structure of the "DID Resolution Result" is documented [here](https://w3c-ccg.github.io/did-resolution/#did-resolution-result). The W3C DID WG is currently considering if some parts of DID Resolution (especially the inputs and outputs) should be included in the [DID Core spec](https://w3c.github.io/did-core/).

We will make sure the inputs/outputs of the Universal Resolver stay aligned with what the DID Core / DID Resolution specs define.

I think we can close this issue for now and open a new one later if needed.
