### ISSUE TITLE
Create a cross-implementation JSON config

### ISSUE THREAD

**Issue by csuwildcat** [decentralized-identity/universal-resolver#25]
Per the related discussion, we should create a shared JSON config file that all implementations use, which should contain at least the following for each DID Method:

- 1 entry per DID Method prefix string
- Tag and version of matching driver image
- Test DID that can be run against the harness/CI
- Default environment variables used by the UR/Driver

**Comment by tsmcalister** [comment]
Is this config being used at all? I'm trying to implement a node.js based resolver but it seems I can't get it to work with the docker-compose setup (The calls aren't being routed to my docker container).

**Comment by peacekeeper** [comment]
Fixed by 3a6128320f3a3a79159795d12835249ceb1804b5. config.json is being used now in conjunction with docker-compose.yml to load and configure drivers.
