### ISSUE TITLE
Migrate Universal Resolver to Spring Boot

### ISSUE THREAD

**Issue by peacekeeper** [decentralized-identity/universal-resolver#259]
Hi all, we are planning to work on migrating the Universal Resolver to the Spring Boot framework, in order to better support logging, metrics, configuration, and other features that could be useful for more professional/enterprise deployments in the future.

This should be fully backwards compatible, i.e. no changes necessary to the external API or driver implementation.

Please let us know if you have any feedback or concerns.

**Comment by solidnerd** [comment]
How does it affect the architecture and which components are targeted here? Let us make a more detailed plan on what will be migrated. So for example I think the main target is here the web component is targeted as migration but for example, drivers aren't needed to do this.  Are also repositories structures changes included ?  

But I'm looking forward to this :)

**Comment by peacekeeper** [comment]
Yes, this is about the web component, not about individual drivers. I don't think repository structures will change.

We'll see about the details once we start working on it, happy to discuss also in DIF Slack!

**Comment by solidnerd** [comment]
@BernhardFuchs  @peacekeeper  @cihanss  I think this breaking change we should bump the version to 2.x or make at least a new version 0.5.x since the packaging has changed completely.
