### ISSUE TITLE
Cant get it working with the local indy setup

### ISSUE THREAD

**Issue by fatjoni** [decentralized-identity/universal-resolver#26]
Hello,

I started the indy sdk by following step 3 in this github url:
https://github.com/hyperledger/indy-sdk/blob/master/README.md#installing-the-sdk
I tried passing all the 4 environment variables and a mixture of them and i get these kind of errors:

If i include the ubuntu binary i get this:
_java.lang.UnsatisfiedLinkError: Unable to load library 'indy': Native library (linux-x86-64/libindy.so) not found in resource path ([file:/opt/driver-did-sov/target/test-classes/,......_

if i remove the binary environment variable i get this:
_Driver reported for did:sov:Th7MpTaRZVRYnPiabds81Y: Cannot create pool config pool1: org.hyperledger.indy.sdk.IOException: An IO error occurred._

I am sure the uniresolver_driver_did_sov_poolGenesisTxn is correct because it is the same path that i use for the indy setup i have referenced above and all the scripts are working.
Please let me know if you can help,
Regards,
Fatjoni

**Comment by azuzi** [comment]
@fatjoni ,

Is this issue still remain with our changes over the time? If so we would like to resolve this issue as soon as possible.

**Comment by azuzi** [comment]
As this issue seems to be outdated I'm closing this issue. Also no reply from @fatjoni .
