### ISSUE TITLE
did:stack method documentation

### ISSUE THREAD

**Issue by jcnelson** [decentralized-identity/universal-resolver#27]
Documented the DID method for did:stack here: https://github.com/blockstack/blockstack-core/blob/master/docs/blockstack-did-spec.md

**Comment by Muhammad-Altabba** [comment]
Hello @jcnelson,
The link is broaken.

**Comment by peacekeeper** [comment]
We looked at this issue on the 23 Jun 2021 Universal Resolver call. It looks like a DID method spec for did:stack exists here: https://github.com/blockstack/stacks-blockchain/blob/stacks-1.0/docs/blockstack-did-spec.md

So I think we can close this. Feel free to re-open if this needs more discussion.
