### ISSUE TITLE
Unable to git clone this project 

### ISSUE THREAD

**Issue by mahoekst** [decentralized-identity/universal-resolver#275]
When I try to git clone the project I fails with this message: error: invalid path 'driver-status-reports/nightly-run-2021-05-26_10:38:17/did-test-suite-report-2021-05-26T10:39:49.json'

**Comment by BernhardFuchs** [comment]
Just did git clone to a clean folder and everything works fine.  
I'm using git with the command line.

**Comment by mahoekst** [comment]
I tried again on linux and it works. It fails on Windows

**Comment by BernhardFuchs** [comment]
Apparently a `:` is an invalid character on NTFS filesystems which I wasn't aware of when I created the script creating these files.  
I got this snippet from [Stackoverflow](https://stackoverflow.com/questions/63727594/github-git-checkout-returns-error-invalid-path-on-windows) which might be a temporary fix `git config core.protectNTFS false`.  
Other than that we have to refactor this script and the already created filepaths.

**Comment by mahoekst** [comment]
ah that was it. My workaround was to do git clone in WSL in my c drive and that worked.

**Comment by BernhardFuchs** [comment]
Yes, on WSL it should work, but after all it's a bug we should fix.  
We don't want devs on Windows to rely on workarounds.

**Comment by mahoekst** [comment]
thanks for addressing this.

**Comment by BernhardFuchs** [comment]
@mahoekst We moved the problematic files to a separate [branch](https://github.com/decentralized-identity/universal-resolver/tree/driver-status-reports/driver-status-reports).  
This was on our backlog for a couple of other reasons too.  
If that fixes the problems with cloning the repo on Windows, feel free to close this issue.
