### ISSUE TITLE
HTTP bindings for deactivated DIDs are ignored

### ISSUE THREAD

**Issue by rflechtner** [decentralized-identity/universal-resolver#289]
Hi,

While improving on the [KILT did driver](https://github.com/KILTprotocol/kilt-did-driver) we realised that the current implementation of the universal resolver for the biggest part follows the did resolution [specs on http bindings](https://w3c-ccg.github.io/did-resolution/#bindings-https), but it seems to disregard the recommendation to flag deactivated DIDs with a `410` status code. We are wondering if that is intentional or whether it is worth fixing?

__Examples__
This way the deactivated status is obvious because of the document metadata:
```curl -v https://dev.uniresolver.io/1.0/identifiers/did:kilt:4r6RdVMNes2eEobxyxH7aVsesUqR2X175sUAXJfo7dEWxHUS```
Requesting only the document, however, obscures this (here the status code could help):
```curl -v -H 'accept: application/did+ld+json' https://dev.uniresolver.io/1.0/identifiers/did:kilt:4r6RdVMNes2eEobxyxH7aVsesUqR2X175sUAXJfo7dEWxHUS```

**Comment by peacekeeper** [comment]
@rflechtner thanks for pointing this out. I think I just fixed this in [35bb7af](https://github.com/decentralized-identity/universal-resolver/commit/35bb7af99eb2605233694ee88da7eba7d2522a20), could you perhaps verify on your end?

@cihanss I think we also talked about this.

**Comment by rflechtner** [comment]
@peacekeeper Thanks for the quick fix, works great on our end! I should probably flag though that the [universal-resolver-frontend](https://github.com/decentralized-identity/universal-resolver-frontend) does not currently handle this status super gracefully yet (see screenshot). Although you can still inspect the data in the remaining tabs, the result page just shows an error message.

<img width="892" alt="Screenshot 2022-03-05 at 20 36 18" src="https://user-images.githubusercontent.com/39338561/156993066-91c0b7ba-3302-425d-beb2-2cfecdfd6ff6.png">

**Comment by peacekeeper** [comment]
@rflechtner Hmm yes there's probably an interesting question.. In HTTP, 4xx codes are considered to be errors, in this case "410 Gone" is also an error. From this perspective, it makes sense that the Universal Resolver frontend displays an error with red background.

However, from a DID perspective, a deactivated DID is not really considered an error, it's just a piece of metadata.

So perhaps mapping "deactivated=true" to 410 isn't 100% semantically correct. On the other hand, as you mention in your original post, it does feel useful to have a dedicated HTTP status code for deactivated DIDs.

**Comment by rflechtner** [comment]
@peacekeeper You got a point there. I fail to come up with a reasonable code from the 2xx or 1xx ranges though. But yes, seems like the Http bindings may need some work

**Comment by peacekeeper** [comment]
@rflechtner can we close this for now? I think if we want to change the behavior, we should discuss it in the DID Resolution spec first rather than here.

**Comment by rflechtner** [comment]
Yes, I agree. The implementation is to spec now, so no issue here. The issue that the http binding is potentially error-prone would belong there. What do you think about the resolver UI handling 410's differently though?
