### ISSUE TITLE
Feature request: support linking to a specific resolution result

### ISSUE THREAD

**Issue by ntn-x2** [decentralized-identity/universal-resolver#292]
Given the current architecture of the resolver, I am not sure if what I am proposing here is achievable or not, but probably is.

It would be, in my opinion, a good addition to add support for GET requests to a specific URL e.g. `https://dev.uniresolver.io/1.0/identifiers/did:kilt:4rNTX3ihuxyWkB7wG3oLgUWSBLa2gva1NBKJsBFm7jJZUYfc` that would show the interface of the universal resolver with the specific method resolution result in there.

The use case would be that of a service providing basic resolution for a given DID and linking to the universal resolver for all the details, including document and resolution metadata. This is currently not possible, AFAICT.

Is this something that makes sense to someone else as well? Are there any major technical obstacles to implementing this feature?

**Comment by peacekeeper** [comment]
@ntn-x2 great idea!

Is this what you mean?

https://dev.uniresolver.io/#did:kilt:4rNTX3ihuxyWkB7wG3oLgUWSBLa2gva1NBKJsBFm7jJZUYfc

**Comment by ntn-x2** [comment]
Exactly! Did not know if was already possible. Thanks for the quick response!
