### ISSUE TITLE
https://dev.uniresolver.io/ is down

### ISSUE THREAD

**Issue by hteramoto** [decentralized-identity/universal-resolver#298]
Hello, 

https://dev.uniresolver.io/ is currently down and returning 502 bad gateway.  Is anyone looking into this?

**Comment by paulgrehan** [comment]
Hi, yes, this is being looked into right now,

**Comment by alejandroalffer** [comment]
Some hours ago, the was a nginx returning http/500 error, now seems a DNS problem... 

```
➜  ~ dig A dev.uniresolver.io

; <<>> DiG 9.16.1-Ubuntu <<>> A dev.uniresolver.io
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 61562
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;dev.uniresolver.io.            IN      A

;; Query time: 40 msec
;; SERVER: 172.21.224.1#53(172.21.224.1)
;; WHEN: Tue Apr 19 16:56:48 CEST 2022
;; MSG SIZE  rcvd: 36
```

**Comment by alejandroalffer** [comment]
There's no DNS records... @peacekeeper, any change in AWS zones?

**Comment by BernhardFuchs** [comment]
@alejandroalffer Thx for investigating on your side.  
Atm we have issues with the underlying infrastructure. We have stuck resources in our K8s cluster and are unable to release them. We are investigating but can't tell how long it will take.  
Sorry for the inconvenience

**Comment by alejandroalffer** [comment]
Thx for the feedback @BernhardFuchs. Good luck and let me know if we can help anyway 💪

**Comment by BernhardFuchs** [comment]
We could indentify the issue as an issue of K8s API version mismatch after our latest work on monitoring and analytic capabilities.  
As a lot of us are busy preparing for IIW, we will postpone further work on these topics till after the conference.  
Sorry for any inconvenience

**Comment by hteramoto** [comment]
@BernhardFuchs , thank you for resolving this issue.  Very much appreciated!
