### ISSUE TITLE
did:sov driver bug - cannot resolve any did - eesdi related

### ISSUE THREAD

**Issue by 0xCaos** [decentralized-identity/universal-resolver#311]
To reproduce, try to resolve any `did:sov`. You'll get this error: 

`Resolve problem for did:sov:WRfXPg8dantKVubE3HX8pw: Cannot open Indy connections: No wallet name for pool: eesdi`

after merging this PR https://github.com/decentralized-identity/universal-resolver/pull/310 you should get a different error:

`Resolve problem for did:sov:WRfXPg8dantKVubE3HX8pw: Cannot open Indy connections: Cannot create pool config "eesdi": org.hyperledger.indy.sdk.IOException: An IO error occurred.`

Tried to fix this in `did:sov` driver but couldn't manage to do it.

**Comment by peacekeeper** [comment]
I just pushed commit https://github.com/decentralized-identity/universal-resolver/commit/39149c23198ae12a043aee54136174bf5de45565 to remove the "eesdi" network, which is outdated. Could you try again now? Also make sure you have the latest version of the `universalresolver/driver-did-sov` image.

**Comment by 0xCaos** [comment]
ok perfect then, it should be fine now! I also managed to resolve did:sov deleting eesdi but I didn't think it was something that could be removed. Thanks!
