### ISSUE TITLE
Each VC required unique DID??

### ISSUE THREAD

**Issue by Muthurajj** [decentralized-identity/universal-resolver#320]
1.Each VC required unique DID?
2.what is the purpose of this library?
3.After creating DID in uniresolver we need to anchor it to blockchain??

**Comment by BernhardFuchs** [comment]
Thx for reaching out.

ad 1) Most concepts have one DID and multiple VCs attached to but this really depends on the use case.  

ad 2) This repo contains the universal-resolver application which is hosted as a free service under [dev.uniresolver.io](https://dev.uniresolver.io/). The only purpose is to resolve DIDs and not to create, update or deactivate them. These operations are done by the [universal-registrar](https://github.com/decentralized-identity/universal-registrar) hosted under https://uniregistrar.io/  

ad 3) DIDs cannot be created with the universal-resolver but some are available at the universal-registrar. Not all DIDs utilize a blockchain to store the record but if they do, the universal-registrar is anchoring it and returns the keys needed to control it.

**Comment by Muthurajj** [comment]
Thanks for the reply @BernhardFuchs 
Can we use this did in production?
Do you have any idea about creating own DID and did document?

**Comment by peacekeeper** [comment]
@Muthurajj Please do **NOT** use https://dev.uniresolver.io/ or https://uniregistrar.io/ in production.

You can download and self-host these open-source components on your own infrastructure (but you're also responsible for securing and maintaining them, etc.).

For production use you can also use a commercial service such as https://godiddy.com/.

**Comment by Muthurajj** [comment]
The difference between uniresolver and uniregistrar is 
resolver cannot create or update its already created DIDs which we can use?
registrar can create or update DIDs ?

**Comment by BernhardFuchs** [comment]
Yes, the Resolver is for resolving the DID document of the DID. It can also be seen as the READ operation.  

Registrar is for CREATE, UPDATE, DELETE of DIDs. But DELETE is not possible for some DIDs, so the terminology used is DEACTIVATE.

**Comment by Muthurajj** [comment]
Thanks for the support @BernhardFuchs

**Comment by BernhardFuchs** [comment]
You're welcome.  
If your questions are answered pls consider closing this issue.  
You can always reopen it or open a new one if needed.
