### ISSUE TITLE
Unable to test Driver for new DID method locally

### ISSUE THREAD

**Issue by nickreynolds** [decentralized-identity/universal-resolver#341]
I'm trying to add support for `did:ens` via the uport driver. I've followed the steps to the best of my ability, but when I run the universal resolver locally and try to resolve a `did:ens` DID, I get an error

```
{
    "@context": "https://w3id.org/did-resolution/v1",
    "didDocument": null,
    "didResolutionMetadata": {
        "error": "methodNotSupported",
        "errorMessage": "Method not supported: ens",
        "contentType": "application/did+ld+json"
    },
    "didDocumentMetadata": {}
}
```

During startup, I see many patterns are added by `WebAppConfig`, but I don't see my new pattern there. Is there something I'm missing to get my new pattern picked up by the config?

I have a branch with my changes here:
https://github.com/nickreynolds/universal-resolver/tree/did-ens

**Comment by nickreynolds** [comment]
Think I fixed this. I think the driver-development.md file is just slightly wrong. Building `uni-resolver-web` locally needs to come after the `docker-compose pull`. I can make another PR to update that doc, unless I'm missing something.

**Comment by peacekeeper** [comment]
> I think the driver-development.md file is just slightly wrong. Building `uni-resolver-web` locally needs to come after the `docker-compose pull`.

I think you may be right about this. Happy to accept a PR to improve this.. Thanks for your input and contributions!
