### ISSUE TITLE
Link in Readme for Indy Driver might be incorrect

### ISSUE THREAD

**Issue by dennisn00** [decentralized-identity/universal-resolver#389]
[PR 378](https://github.com/decentralized-identity/universal-resolver/pull/378) replaces the indy-did-driver with driver-did-indy.
The Readme does not seem to be updated and still links to the (old) IDUnion indy-did-driver

**Comment by dennisn00** [comment]
I opened a [Pull Request](https://github.com/decentralized-identity/universal-resolver/pull/393) to fix this

**Comment by peacekeeper** [comment]
Thanks for your contribution! I merged your PR.
