### ISSUE TITLE
Update did:example PR to use a specific version and not "latest"

### ISSUE THREAD

**Issue by kimdhamilton** [decentralized-identity/universal-resolver#399]
Let's update the did:example PR to use a specific version and not "latest" so that new contributors use the best practice

https://github.com/decentralized-identity/universal-resolver/pull/100/files

**Comment by peacekeeper** [comment]
@kimdhamilton Good idea, done now! Also done in https://github.com/decentralized-identity/universal-registrar/pull/7/files
