### ISSUE TITLE
Resolve problem for did:btcr:xkrn-xzcr-qqlv-j6sl

### ISSUE THREAD

**Issue by adityaishan** [decentralized-identity/universal-resolver#40]
When i am running the curl command 
> curl -X GET  http://localhost:8080/1.0/identifiers/did:btcr:xkrn-xzcr-qqlv-j6sl

it's displaying this.
> Resolve problem for did:btcr:xkrn-xzcr-qqlv-j6sl: Driver reported for did:btcr:xkrn-xzcr-qqlv-j6sl: Index: 0, Size: 0

Can anyone explain what does it mean?

**Comment by OR13** [comment]
I get a similar error here:

```
Resolve problem for did:btcr:xkrn-xzcr-qqlv-j6sl: Driver reported for did:btcr:xkrn-xzcr-qqlv-j6sl: Index: 120, Size: 96
```

https://uniresolver.io/

**Comment by OR13** [comment]
some things to check:

- what is the txid for this did?
- is the continuation format correct?

**Comment by adityaishan** [comment]
curl -X GET http://localhost:8080/1.0/identifiers/did:v1:test:nym:3AEJTDMSxDDQpyUftjuoeZ2Bazp4Bswj1ce7FJGybCUu
> No resolve result for did:v1:test:nym:3AEJTDMSxDDQpyUftjuoeZ2Bazp4Bswj1ce7FJGybCUu.

 curl -X GET http://localhost:8080/1.0/identifiers/did:ipid:QmYA7p467t4BGgBL4NmyHtsXMoPrYH9b3kSG6dbgFYskJm
> Resolve problem for did:ipid:QmYA7p467t4BGgBL4NmyHtsXMoPrYH9b3kSG6dbgFYskJm: ipfs resolve -r /ipns/QmYA7p467t4BGgBL4NmyHtsXMoPrYH9b3kSG6dbgFYskJm: context deadline exceeded

curl -X GET  http://localhost:8080/1.0/identifiers/did:stack:v0:16EMaNw3pkn3v6f2BgnSSs53zAKH4Q8YJg-0
> Resolve problem for did:stack:v0:16EMaNw3pkn3v6f2BgnSSs53zAKH4Q8YJg-0: Driver reported for did:stack:v0:16EMaNw3pkn3v6f2BgnSSs53zAKH4Q8YJg-0: Cannot retrieve DDO for `blockstacknewyear2017.id` from `https://core.blockstack.org/v1/users/blockstacknewyear2017.id: HTTP/1.1 404 NOT FOUND

These curl commands are also giving errors, any suggestion how to resolve them.

**Comment by adityaishan** [comment]
> @adityaishan and @OR13
> 
> Your example `did:btcr:xkrn-xzcr-qqlv-j6sl` is based on the outdated 4-4-4-4 pattern. I updated the Universal Resolver last week during the [BTCR hackathon](https://weboftrustinfo.github.io/btcr-hackathon-2019/), and you can now see some updated examples at https://uniresolver.io/. The current format is now either 4-4-3 or 4-4-4-2.
> 
> The specification that defines the identifier pattern is called BIP 136: https://github.com/bitcoin/bips/blob/master/bip-0136.mediawiki
> 
> Also see here for a deeper technical discussion: [w3c-ccg/didm-btcr#1](https://github.com/w3c-ccg/didm-btcr/issues/1)
> 
> Sorry for the meaningless error message you got.

You got some typo, instead of 4-4-3 it would be 4-4-4-3 pattern.

**Comment by peacekeeper** [comment]
@adityaishan You are correct of course, thanks for pointing out the typo. I just fixed it in my earlier message.

**Comment by azuzi** [comment]
As mentioned by @peacekeeper , this outdated 4-4-4-4 pattern and correct curl request for btcr is 
"curl -X GET http://localhost:8080/1.0/identifiers/did:btcr:xz35-jznz-q6mr-7q6 " .
