### ISSUE TITLE
Need to update config.json for did:btcr

### ISSUE THREAD

**Issue by adityaishan** [decentralized-identity/universal-resolver#43]
As we have seen earlier (https://github.com/decentralized-identity/universal-resolver/issues/40) did:btcr are following 4-4-4-3 or 4-4-4-2 pattern and not 4-4-4-4 pattern. So we need to update the 
>`testIdentifiers` of  `did:btcr` driver in config.json.

**Comment by peacekeeper** [comment]
Agreed, thanks for pointing this out!
