### ISSUE TITLE
Wrong version of DID specs in the README

### ISSUE THREAD

**Issue by gjgd** [decentralized-identity/universal-resolver#46]
In the [Driver section of the README as of commit e5f1418](https://github.com/decentralized-identity/universal-resolver/tree/e5f1418884cdf8a7fd11c26d51e27382a52ad826#drivers) all drivers declare following DID Spec version 0.11, however the [link](https://w3c-ccg.github.io/did-spec/) points to the latest version which is currently 0.13

**Comment by peacekeeper** [comment]
Good point; we should probably just link to the [Final Community Group Report](https://w3c-ccg.github.io/did-spec/CGFR/2019-08-10/) for now (in practice, I don't think we really have accurate information which version of the DID Spec a certain driver actually supports).
