### ISSUE TITLE
Add Documentation for HTTP Proxy drivers

### ISSUE THREAD

**Issue by gjgd** [decentralized-identity/universal-resolver#47]
The [documentation](https://github.com/decentralized-identity/universal-resolver/blob/e5f1418884cdf8a7fd11c26d51e27382a52ad826/docs/driver-development.md) currently explains how to contribute a Driver in the form of a Docker container, but should also mention how to contribute a driver in the form of an HTTP Proxy (eg did:ipid, did:elem)

**Comment by peacekeeper** [comment]
+1 good point. In the DID Resolution spec this is known as the [HTTP(S) Binding](https://w3c-ccg.github.io/did-resolution/#bindings-https), and I agree this should be mentioned in the UR docs.

**Comment by azuzi** [comment]
HTTP(S) Binding added to [driver-development](https://github.com/decentralized-identity/universal-resolver/blob/master/docs/driver-development.md).
