### ISSUE TITLE
Can't locate dependencies for `org.hyperledger.indy`

### ISSUE THREAD

**Issue by adityaishan** [decentralized-identity/universal-resolver#49]
My project is not able to resolve org.hyperledger.indy packages. Need the dependencies for pom.xml as i am not able to find online. 

> import org.hyperledger.indy.sdk.IndyException;
> import org.hyperledger.indy.sdk.LibIndy;
> import org.hyperledger.indy.sdk.did.Did;
> import org.hyperledger.indy.sdk.did.DidJSONParameters.CreateAndStoreMyDidJSONParameter;
> import org.hyperledger.indy.sdk.did.DidResults.CreateAndStoreMyDidResult;
> import org.hyperledger.indy.sdk.ledger.Ledger;
> import org.hyperledger.indy.sdk.pool.Pool;
> import org.hyperledger.indy.sdk.pool.PoolJSONParameters.CreatePoolLedgerConfigJSONParameter;
> import org.hyperledger.indy.sdk.pool.PoolJSONParameters.OpenPoolLedgerJSONParameter;
> import org.hyperledger.indy.sdk.pool.PoolLedgerConfigExistsException;
> import org.hyperledger.indy.sdk.wallet.Wallet;
> import org.hyperledger.indy.sdk.wallet.WalletExistsException;

Can you provide the dependencies for org.hyperledger.indy

**Comment by peacekeeper** [comment]
Hello, this dependency is from the [Hyperledger Indy](https://www.hyperledger.org/indy) project, you can include a separate Maven repository in your `pom.xml` to use it:

```
    <repository>
        <id>sovrin</id>
        <url>https://repo.sovrin.org/repository/maven-public</url>
    </repository>
```

And then add the dependency as follows:

```
    <dependency>
        <groupId>org.hyperledger</groupId>
        <artifactId>indy</artifactId>
        <version>1.8.2</version>
    </dependency>
```

Alternatively, you can also build the source code manually from here:

https://github.com/hyperledger/indy-sdk/tree/master/wrappers/java

You can also build the `sov` driver using Docker, in that case everything should happen automatically:

https://github.com/decentralized-identity/universal-resolver/tree/master/drivers/sov

https://github.com/decentralized-identity/universal-resolver/blob/master/drivers/sov/docker/Dockerfile

**Comment by peacekeeper** [comment]
We looked at this on the 30 Jun 2021 Universal Resolver call and decided to close, since 1. there hasn't been any reply to the last message, and 2. this is probably more relevant to the did:sov driver in this repository: https://github.com/decentralized-identity/uni-resolver-driver-did-sov/

@adityaishan feel free to re-open this, or open a new issues in the did:sov driver repository if there is still a problem.
