### ISSUE TITLE
How to set  libindy path?

### ISSUE THREAD

**Issue by AnkitAtmecs** [decentralized-identity/universal-resolver#52]
I have followed the documentation for universal resolver of resolver/java, I was able to build and run **did:btcr**  but while working with **did:sov** driver. I need to set  '_SetLibindyPath_', '_SetPoolConfigurationName_', '_setPoolGenesisTxn_' .

 i am trying to setup libindy path as follow:
> uniResolver.getDriver(DidSovDriver.class).setLibIndyPath("/home/ankitshrivastava/universal-resolver/drivers/sov/sovrin");

But getting following error:

> java.lang.UnsatisfiedLinkError: Unable to load library '/home/ankitshrivastava/universal-resolver/drivers/sov/sovrin': Native library (home/ankitshrivastava/universal-resolver/drivers/sov/sovrin) not found in resource path ([file:/home/ankitshrivastava/Documents/workspace-again/demo/target/classes/, file:/home/ankitshrivastava/universalResolver/universal-resolver/resolver/java/uni-resolver-client/target/classes/, file:/home/ankitshrivastava/universalResolver/universal-resolver/resolver/java/uni-resolver-core/target/classes/, file:/home/ankitshrivastava/universalResolver/did-common-java/target/classes/, file:/home/ankitshrivastava/.m2/repository/com/github/jsonld-java/jsonld-java/0.12.3/jsonld-java-0.12.3.jar, file:/home/ankitshrivastava/.m2/repository/org/apache/httpcomponents/httpclient-osgi/4.5.9/httpclient-osgi-4.5.9.jar, file:/home/ankitshrivastava/.m2/repository/org/apache/httpcomponents/httpmime/4.5.9/httpmime-4.5.9.jar, file:/home/ankitshrivastava/.m2/repository/org/apache/httpcomponents/httpclient-cache/4.5.9/httpclient-cache-4.5.9.jar, file:/home/ankitshrivastava/.m2/repository/org/apache/httpcomponents/fluent-hc/4.5.9/fluent-hc-4.5.9.jar, file:/home/ankitshrivastava/.m2/repository/org/apache/httpcomponents/httpcore-osgi/4.4.10/httpcore-osgi-4.4.10.jar, file:/home/ankitshrivastava/.m2/repository/org/apache/httpcomponents/httpcore-nio/4.4.12/httpcore-nio-4.4.12.jar, file:/home/ankitshrivastava/.m2/repository/org/apache/httpcomponents/httpclient/4.5.9/httpclient-4.5.9.jar, file:/home/ankitshrivastava/.m2/repository/org/apache/httpcomponents/httpcore/4.4.12/httpcore-4.4.12.jar, file:/home/ankitshrivastava/.m2/repository/org/springframework/boot/spring-boot-starter-web/2.1.8.RELEASE/spring-boot-starter-web-2.1.8.RELEASE.jar, file:/home/ankitshrivastava/.m2/repository/org/springframework/boot/spring-boot-starter/2.1.8.RELEASE/spring-boot-starter-2.1.8.RELEASE.jar, file:/home/ankitshrivastava/.m2/repository/org/springframework/boot/spring-boot/2.1.8.RELEASE/spring-boot-2.1.8.RELEASE.jar, file:/home/ankitshrivastava/.m2/repository/org/springframework/boot/spring-boot-autoconfigure/2.1.8.RELEASE/spring-boot-autoconfigure-2.1.8.RELEASE.jar, file:/home/ankitshrivastava/.m2/repository/org/springframework/boot/spring-boot-starter-logging/2.1.8.RELEASE/spring-boot-starter-logging-2.1.8.RELEASE.jar, file:/home/ankitshrivastava/.m2/repository/ch/qos/logback/logback-classic/1.2.3/logback-classic-1.2.3.jar, file:/home/ankitshrivastava/.m2/repository/ch/qos/logback/logback-core/1.2.3/logback-core-1.2.3.jar, file:/home/ankitshrivastava/.m2/repository/org/apache/logging/log4j/log4j-to-slf4j/2.11.2/log4j-to-slf4j-2.11.2.jar, file:/home/ankitshrivastava/.m2/repository/javax/annotation/javax.annotation-api/1.3.2/javax.annotation-api-1.3.2.jar, file:/home/ankitshrivastava/.m2/repository/org/yaml/snakeyaml/1.23/snakeyaml-1.23.jar, file:/home/ankitshrivastava/.m2/repository/org/springframework/boot/spring-boot-starter-json/2.1.8.RELEASE/spring-boot-starter-json-2.1.8.RELEASE.jar, file:/home/ankitshrivastava/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.9.9.3/jackson-databind-2.9.9.3.jar, file:/home/ankitshrivastava/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.9.0/jackson-annotations-2.9.0.jar, file:/home/ankitshrivastava/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.9.9/jackson-core-2.9.9.jar, file:/home/ankitshrivastava/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-jdk8/2.9.9/jackson-datatype-jdk8-2.9.9.jar, file:/home/ankitshrivastava/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-jsr310/2.9.9/jackson-datatype-jsr310-2.9.9.jar, file:/home/ankitshrivastava/.m2/repository/com/fasterxml/jackson/module/jackson-module-parameter-names/2.9.9/jackson-module-parameter-names-2.9.9.jar, file:/home/ankitshrivastava/.m2/repository/org/springframework/boot/spring-boot-starter-tomcat/2.1.8.RELEASE/spring-boot-starter-tomcat-2.1.8.RELEASE.jar, file:/home/ankitshrivastava/.m2/repository/org/apache/tomcat/embed/tomcat-embed-core/9.0.24/tomcat-embed-core-9.0.24.jar, file:/home/ankitshrivastava/.m2/repository/org/apache/tomcat/embed/tomcat-embed-el/9.0.24/tomcat-embed-el-9.0.24.jar, file:/home/ankitshrivastava/.m2/repository/org/apache/tomcat/embed/tomcat-embed-websocket/9.0.24/tomcat-embed-websocket-9.0.24.jar, file:/home/ankitshrivastava/.m2/repository/org/hibernate/validator/hibernate-validator/6.0.17.Final/hibernate-validator-6.0.17.Final.jar, file:/home/ankitshrivastava/.m2/repository/javax/validation/validation-api/2.0.1.Final/validation-api-2.0.1.Final.jar, file:/home/ankitshrivastava/.m2/repository/org/jboss/logging/jboss-logging/3.3.3.Final/jboss-logging-3.3.3.Final.jar, file:/home/ankitshrivastava/.m2/repository/com/fasterxml/classmate/1.4.0/classmate-1.4.0.jar, file:/home/ankitshrivastava/.m2/repository/org/springframework/spring-web/5.1.9.RELEASE/spring-web-5.1.9.RELEASE.jar, file:/home/ankitshrivastava/.m2/repository/org/springframework/spring-beans/5.1.9.RELEASE/spring-beans-5.1.9.RELEASE.jar, file:/home/ankitshrivastava/.m2/repository/org/springframework/spring-webmvc/5.1.9.RELEASE/spring-webmvc-5.1.9.RELEASE.jar, file:/home/ankitshrivastava/.m2/repository/org/springframework/spring-aop/5.1.9.RELEASE/spring-aop-5.1.9.RELEASE.jar, file:/home/ankitshrivastava/.m2/repository/org/springframework/spring-context/5.1.9.RELEASE/spring-context-5.1.9.RELEASE.jar, file:/home/ankitshrivastava/.m2/repository/org/springframework/spring-expression/5.1.9.RELEASE/spring-expression-5.1.9.RELEASE.jar, file:/home/ankitshrivastava/.m2/repository/org/springframework/spring-core/5.1.9.RELEASE/spring-core-5.1.9.RELEASE.jar, file:/home/ankitshrivastava/.m2/repository/org/springframework/spring-jcl/5.1.9.RELEASE/spring-jcl-5.1.9.RELEASE.jar, file:/home/ankitshrivastava/universalResolver/universal-resolver/resolver/java/uni-resolver-local/target/classes/, file:/home/ankitshrivastava/universalResolver/universal-resolver/resolver/java/driver/target/classes/, file:/home/ankitshrivastava/universalResolver/universal-resolver/resolver/java/driver-http/target/classes/, file:/home/ankitshrivastava/universalResolver/universal-resolver/drivers/sov/target/classes/, file:/home/ankitshrivastava/.m2/repository/com/google/code/gson/gson/2.8.5/gson-2.8.5.jar, file:/home/ankitshrivastava/universalResolver/universal-resolver/drivers/btcr/target/classes/, file:/home/ankitshrivastava/btc-tx-lookup-java/target/classes/, file:/home/ankitshrivastava/libtxref-java/target/classes/, file:/home/ankitshrivastava/libbech32-java/target/classes/, file:/home/ankitshrivastava/.m2/repository/wf/bitcoin/JavaBitcoindRpcClient/1.0.0/JavaBitcoindRpcClient-1.0.0.jar, file:/home/ankitshrivastava/.m2/repository/com/github/briandilley/jsonrpc4j/jsonrpc4j/1.5.3/jsonrpc4j-1.5.3.jar, file:/home/ankitshrivastava/.m2/repository/net/iharder/base64/2.3.9/base64-2.3.9.jar, file:/home/ankitshrivastava/.m2/repository/commons-io/commons-io/2.6/commons-io-2.6.jar, file:/home/ankitshrivastava/.m2/repository/org/bitcoinj/bitcoinj-core/0.15.2/bitcoinj-core-0.15.2.jar, file:/home/ankitshrivastava/.m2/repository/org/bouncycastle/bcprov-jdk15on/1.60/bcprov-jdk15on-1.60.jar, file:/home/ankitshrivastava/.m2/repository/com/google/protobuf/protobuf-java/3.6.1/protobuf-java-3.6.1.jar, file:/home/ankitshrivastava/.m2/repository/com/lambdaworks/scrypt/1.4.0/scrypt-1.4.0.jar, file:/home/ankitshrivastava/.m2/repository/com/google/guava/guava/27.0.1-android/guava-27.0.1-android.jar, file:/home/ankitshrivastava/.m2/repository/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar, file:/home/ankitshrivastava/.m2/repository/com/google/guava/listenablefuture/9999.0-empty-to-avoid-conflict-with-guava/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar, file:/home/ankitshrivastava/.m2/repository/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar, file:/home/ankitshrivastava/.m2/repository/org/checkerframework/checker-compat-qual/2.5.2/checker-compat-qual-2.5.2.jar, file:/home/ankitshrivastava/.m2/repository/com/google/errorprone/error_prone_annotations/2.2.0/error_prone_annotations-2.2.0.jar, file:/home/ankitshrivastava/.m2/repository/com/google/j2objc/j2objc-annotations/1.1/j2objc-annotations-1.1.jar, file:/home/ankitshrivastava/.m2/repository/org/codehaus/mojo/animal-sniffer-annotations/1.17/animal-sniffer-annotations-1.17.jar, file:/home/ankitshrivastava/.m2/repository/com/squareup/okhttp3/okhttp/3.12.1/okhttp-3.12.1.jar, file:/home/ankitshrivastava/.m2/repository/com/squareup/okio/okio/1.15.0/okio-1.15.0.jar, file:/home/ankitshrivastava/.m2/repository/net/jcip/jcip-annotations/1.0/jcip-annotations-1.0.jar, file:/home/ankitshrivastava/.m2/repository/commons-codec/commons-codec/1.11/commons-codec-1.11.jar, file:/home/ankitshrivastava/.m2/repository/org/springframework/boot/spring-boot-starter-actuator/2.1.8.RELEASE/spring-boot-starter-actuator-2.1.8.RELEASE.jar, file:/home/ankitshrivastava/.m2/repository/org/springframework/boot/spring-boot-actuator-autoconfigure/2.1.8.RELEASE/spring-boot-actuator-autoconfigure-2.1.8.RELEASE.jar, file:/home/ankitshrivastava/.m2/repository/org/springframework/boot/spring-boot-actuator/2.1.8.RELEASE/spring-boot-actuator-2.1.8.RELEASE.jar, file:/home/ankitshrivastava/.m2/repository/io/micrometer/micrometer-core/1.1.6/micrometer-core-1.1.6.jar, file:/home/ankitshrivastava/.m2/repository/org/hdrhistogram/HdrHistogram/2.1.9/HdrHistogram-2.1.9.jar, file:/home/ankitshrivastava/.m2/repository/org/latencyutils/LatencyUtils/2.0.3/LatencyUtils-2.0.3.jar, file:/home/ankitshrivastava/.m2/repository/org/springframework/boot/spring-boot-starter-log4j2/2.1.8.RELEASE/spring-boot-starter-log4j2-2.1.8.RELEASE.jar, file:/home/ankitshrivastava/.m2/repository/org/apache/logging/log4j/log4j-slf4j-impl/2.11.2/log4j-slf4j-impl-2.11.2.jar, file:/home/ankitshrivastava/.m2/repository/org/apache/logging/log4j/log4j-api/2.11.2/log4j-api-2.11.2.jar, file:/home/ankitshrivastava/.m2/repository/org/apache/logging/log4j/log4j-core/2.11.2/log4j-core-2.11.2.jar, file:/home/ankitshrivastava/.m2/repository/org/apache/logging/log4j/log4j-jul/2.11.2/log4j-jul-2.11.2.jar, file:/home/ankitshrivastava/.m2/repository/org/slf4j/jul-to-slf4j/1.7.28/jul-to-slf4j-1.7.28.jar, file:/home/ankitshrivastava/.m2/repository/org/slf4j/slf4j-api/1.7.28/slf4j-api-1.7.28.jar, file:/home/ankitshrivastava/.m2/repository/org/slf4j/jcl-over-slf4j/1.7.28/jcl-over-slf4j-1.7.28.jar, file:/home/ankitshrivastava/.m2/repository/org/slf4j/slf4j-log4j12/1.7.28/slf4j-log4j12-1.7.28.jar, file:/home/ankitshrivastava/.m2/repository/log4j/log4j/1.2.17/log4j-1.2.17.jar, file:/home/ankitshrivastava/indy-sdk/wrappers/java/target/classes/, file:/home/ankitshrivastava/.m2/repository/net/java/dev/jna/jna/4.5.2/jna-4.5.2.jar, file:/home/ankitshrivastava/.m2/repository/org/apache/commons/commons-lang3/3.8.1/commons-lang3-3.8.1.jar, file:/home/ankitshrivastava/.m2/repository/org/json/json/20180130/json-20180130.jar])
> 	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:303) ~[jna-4.5.2.jar:4.5.2 (b0)]
> 	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:427) ~[jna-4.5.2.jar:4.5.2 (b0)]
> 	at com.sun.jna.Library$Handler.<init>(Library.java:179) ~[jna-4.5.2.jar:4.5.2 (b0)]
> 	at com.sun.jna.Native.loadLibrary(Native.java:569) ~[jna-4.5.2.jar:4.5.2 (b0)]
> 	at com.sun.jna.Native.loadLibrary(Native.java:544) ~[jna-4.5.2.jar:4.5.2 (b0)]
> 	at org.hyperledger.indy.sdk.LibIndy.init(LibIndy.java:242) ~[classes/:na]
> 	at uniresolver.driver.did.sov.DidSovDriver.openIndy(DidSovDriver.java:282) ~[classes/:na]
> 	at uniresolver.driver.did.sov.DidSovDriver.resolve(DidSovDriver.java:131) ~[classes/:na]
> 	at uniresolver.local.LocalUniResolver.resolve(LocalUniResolver.java:119) ~[classes/:na]
> 	at uniresolver.local.LocalUniResolver.resolve(LocalUniResolver.java:49) ~[classes/:na]
> 	at com.example.demo.service.ResolverService.getDocumentSov(ResolverService.java:153) ~[classes/:na]
> 	at com.example.demo.controller.HomeController.helloagain1(HomeController.java:44) ~[classes/:na]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_222]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_222]
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_222]

**Comment by peacekeeper** [comment]
@AnkitAtmecs sorry that we never responded to this. I guess you somehow solved this in the meantime? Can we close this issue?

One possibility is that there was a bug in the code back then, which has been fixed in the meantime.

Another idea is that you have to pass the full path to the actual libindy library file, rather than just the path to its location.

In the future, issues about the did:sov driver should be created here: https://github.com/decentralized-identity/uni-resolver-driver-did-sov/.

**Comment by peacekeeper** [comment]
We look at this on the [06-Oct-2021 Universal Resolver Work Item Call](https://github.com/decentralized-identity/identifiers-discovery/blob/main/agenda.md#special-work-item-calls) and decided to close this.

Feel free to re-open if you still have problems with this.
