### ISSUE TITLE
Add Better Linking UX

### ISSUE THREAD

**Issue by OR13** [decentralized-identity/universal-resolver#54]
It would be nice to be able to easily link to a Resolved DID.

There should be a button with the text "Share" or similar, that copies a url of the form:

`https://uniresolver.io/#did:btcr:xxcl-lzpq-q83a-0d5`

It should be accent colored to draw attention to it.

There should also be a QR Code which maps to an endpoint which either resolves to `https://uniresolver.io/#did:btcr:xxcl-lzpq-q83a-0d5` or the json representation, depending on request headers.

This will allow clients to decide if they want to show the DID or get its data.

**Comment by peacekeeper** [comment]
Good points! This should probably go into the other repo that has the frontend: https://github.com/decentralized-identity/universal-resolver-frontend/

**Comment by azuzi** [comment]
The issue related to UR Front End and a issue is already opened .
