### ISSUE TITLE
Error when running docker-compose (with latest docker version)

### ISSUE THREAD

**Issue by maudnals** [decentralized-identity/universal-resolver#60]
When following the quick start steps (https://github.com/decentralized-identity/universal-resolver#quick-start):

`docker-compose -f docker-compose.yml pull` returns the following error:
"In file ./.env: environment variable name 'ENV uniresolver_driver_did_erc725_etherscanApis' may not contains whitespace."

Note: if you're reading this and want to fix this issue temporarily and locally, you might want to remove `ENV ` on line 12 of the `.env` file.

**Comment by peacekeeper** [comment]
@maudnals thanks for reporting.. I think I just fixed this in 0145005edcb5ca8225c50f7e84e3cd6d44d43078, could you perhaps check if it works for you now?

**Comment by maudnals** [comment]
@peacekeeper Hi, yes it does, same as my local fix - thanks!
