### ISSUE TITLE
Not able to resolve testnet.veres.one DID

### ISSUE THREAD

**Issue by mocha384** [decentralized-identity/universal-resolver#73]
Universal Resolver is not able to resolve the DID issued on testnet.veres.one. 

![image](https://user-images.githubusercontent.com/1908301/72621932-29193800-3910-11ea-903c-5a975d64d41d.png)

**Comment by msporny** [comment]
> Not able to resolve testnet.veres.one DID

Hmm... Network is up (we haven't gotten any alarms from the network, it seems to be humming along just fine)... https://status.testnet.veres.one/

The correct address for some of the nodes are:

https://alturas.bee.veres.one/
https://tokyo.bee.veres.one/
https://mumbai.bee.veres.one/
https://frankfurt.bee.veres.one/
https://singapore.bee.veres.one/
https://saopaulo.bee.veres.one/
https://genesis.bee.veres.one/

Without looking, my guess here is that we decommissioned the Veres One "Allegheny Ant" Veres One testnet last summer (2018.2-2019.9) and are now on to the "Blueberry Bee" testnet (2019.5-??). "Cavy Capybara" testnet is being readied for release in the coming months.

I'm guessing that maybe the DIF Universal Resolver is using an old testnet that has been decommissioned? Is this issue intermittent?

**Comment by peacekeeper** [comment]
Thanks @mocha384 for reporting, and thanks @msporny for your input. I was able to debug this, apparently the Veres One endpoints used by the Universal Resolver were correct, but the Accept header was wrong. Should be fixed in d9b122f94c6201893715267f0a8ec8aa2008ab24 and the fix has already been deployed at https://uniresolver.io/.

**Comment by msporny** [comment]
> the Accept header was wrong. Should be fixed in d9b122f and the fix has already been deployed at https://uniresolver.io/.

Wonderful, thank you @peacekeeper ! :)

**Comment by peacekeeper** [comment]
@mocha384 if you can also confirm that it works for you now, can you close the issue?

**Comment by mocha384** [comment]
Awesome, it's working as expected.

Thanks a lot, @peacekeeper @msporny

**Comment by msporny** [comment]
> the Accept header was wrong

Just curious, were you sending "application/json" or "application/ld+json"? Both should have worked.

**Comment by mocha384** [comment]
Checked uniresolver.io and it uses application/json in the request header.

**Comment by peacekeeper** [comment]
> Just curious, were you sending "application/json" or "application/ld+json"? Both should have worked.

I was sending `application/ld+json;profile="https://w3c-ccg.github.io/did-resolution/"`, which is something I temporarily invented, thinking that it may be used for requesting a [DID Resolution Result](https://w3c-ccg.github.io/did-resolution/#did-resolution-result) (a data structure that includes the DID document plus metadata).

I'm now sending the following super long Accept header:

`application/ld+json;profile="https://w3c-ccg.github.io/did-resolution/",application/did+ld+json,application/ld+json`

I expect this to change once certain ongoing DID-related discussions (about data formats, metadata, etc.) get decided.

**Comment by msporny** [comment]
> I was sending application/ld+json;profile="https://w3c-ccg.github.io/did

Just to make sure we're not miscommunicating... it was that Accept header that resulted in Veres One nodes returning a 500 error code?

If so, I'll have to check w/ the Veres One devs to see if that's the right response. For example, if the Veres One node looked at "profile" and said, "I can't give you a JSON-LD response in that format", then that might be the right thing to do. However, if the current JSON-LD spec states that you can ignore profile and return application/ld+json if you have it, and the Veres One node didn't do that, then we have a problem w/ the Veres One node software.

In any case, returning 500 is the wrong thing to do, we should've been either returning a "200 OK" or "406 Not Acceptable"

**Comment by peacekeeper** [comment]
@msporny the Universal Resolver sent a bad Accept header to Veres One [2], and Veres One responded with a 406 [3]. The Universal Resolver then threw an error and returned 500 to its client [4]. So nothing was wrong at all with the Veres One nodes.

```
 _____________
|             |
|  VERES ONE  |
|_____________|

    ^     |
    |     |
    | 2   | 3
    |     v
 _____________
|             |
| UNIRESOLVER |
|_____________|

    ^     |
    |     |
    | 1   | 4
    |     v
 _____________
|             |
| C L I E N T |
|_____________|
```

**Comment by msporny** [comment]
> The Universal Resolver sent a bad Accept header to Veres One [2], and Veres One responded with a 406 [3]. The Universal Resolver then threw an error and returned 500 to its client [4]. So nothing was wrong at all with the Veres One nodes.

Ah, ok, got it. Thanks for taking the time to explain, @peacekeeper. Bonus points for ASCII art. :)
