### ISSUE TITLE
Resolver error possibly JSON-LD related

### ISSUE THREAD

**Issue by OR13** [decentralized-identity/universal-resolver#75]
https://element-did.com/api/v1/sidetree/did:elem:EiChaglAoJaBq7bGWp6bA5PAQKaOTzVHVXIlJqyQbljfmg

https://uniresolver.io/#did:elem:EiChaglAoJaBq7bGWp6bA5PAQKaOTzVHVXIlJqyQbljfmg

We have updated our context to an array to demonstrate an interop solution for extending contexts

Its possible that these values are causing errors:

https://docs.element-did.com/contexts/sidetree/sidetree-v0.1.jsonld

**Comment by OR13** [comment]
Proof that the [did document is valid JSON-LD](https://json-ld.org/playground/#startTab=tab-signed-rsa&json-ld=%7B%22%40context%22%3A%5B%7B%22%40version%22%3A1.1%7D%2C%22https%3A%2F%2Fwww.w3.org%2Fns%2Fdid%2Fv1%22%2C%22https%3A%2F%2Fdocs.element-did.com%2Fcontexts%2Fsidetree%2Fsidetree-v0.1.jsonld%22%2C%22https%3A%2F%2Fw3id.org%2Fsecurity%2Fv2%22%5D%2C%22publicKey%22%3A%5B%7B%22publicKeyJwk%22%3A%7B%22x%22%3A%22NbASvplLIO_XTzP9R69a3MuqOO0DQw2LGnhJjirpd4w%22%2C%22kty%22%3A%22EC%22%2C%22crv%22%3A%22secp256k1%22%2C%22y%22%3A%22EiZOvo9JWPz1yGlNNW66IV8uA44EQP_Yv_E7OZl1NG0%22%2C%22kid%22%3A%22qfknmVDhMi3Uc190IHBRfBRqMgbEEBRzWOj1E9EmzwM%22%7D%2C%22type%22%3A%22EcdsaSecp256k1VerificationKey2019%22%2C%22id%22%3A%22%23qfknmVDhMi3Uc190IHBRfBRqMgbEEBRzWOj1E9EmzwM%22%2C%22usage%22%3A%22signing%22%2C%22controller%22%3A%22did%3Aelem%3AEiChaglAoJaBq7bGWp6bA5PAQKaOTzVHVXIlJqyQbljfmg%22%7D%2C%7B%22publicKeyHex%22%3A%220335b012be994b20efd74f33fd47af5adccbaa38ed03430d8b1a78498e2ae9778c%22%2C%22type%22%3A%22EcdsaSecp256k1VerificationKey2019%22%2C%22id%22%3A%22%23primary%22%2C%22usage%22%3A%22signing%22%2C%22controller%22%3A%22did%3Aelem%3AEiChaglAoJaBq7bGWp6bA5PAQKaOTzVHVXIlJqyQbljfmg%22%7D%2C%7B%22type%22%3A%22EcdsaSecp256k1VerificationKey2019%22%2C%22id%22%3A%22%23recovery%22%2C%22usage%22%3A%22recovery%22%2C%22publicKeyHex%22%3A%2203f4c82cee043eeb8dbed2bf02a6b9b066c742557816a738f74a6e4dfd2bbc6469%22%2C%22controller%22%3A%22did%3Aelem%3AEiChaglAoJaBq7bGWp6bA5PAQKaOTzVHVXIlJqyQbljfmg%22%7D%2C%7B%22type%22%3A%22Ed25519VerificationKey2018%22%2C%22publicKeyBase58%22%3A%225gjvqgVsgJYsTaxmVdZ4jtPfgafe7FkvAKF2xRLtkW3H%22%2C%22id%22%3A%22%23PiF0Sf3wDqec9_LYGO5T5-i4ihm7byhbUpoMq2nhZBg%22%2C%22usage%22%3A%22signing%22%2C%22controller%22%3A%22did%3Aelem%3AEiChaglAoJaBq7bGWp6bA5PAQKaOTzVHVXIlJqyQbljfmg%22%7D%5D%2C%22capabilityInvocation%22%3A%5B%22%23qfknmVDhMi3Uc190IHBRfBRqMgbEEBRzWOj1E9EmzwM%22%2C%22%23primary%22%2C%22%23recovery%22%2C%22%23PiF0Sf3wDqec9_LYGO5T5-i4ihm7byhbUpoMq2nhZBg%22%5D%2C%22authentication%22%3A%5B%22%23qfknmVDhMi3Uc190IHBRfBRqMgbEEBRzWOj1E9EmzwM%22%2C%22%23primary%22%2C%22%23recovery%22%2C%22%23PiF0Sf3wDqec9_LYGO5T5-i4ihm7byhbUpoMq2nhZBg%22%5D%2C%22capabilityDelegation%22%3A%5B%22%23qfknmVDhMi3Uc190IHBRfBRqMgbEEBRzWOj1E9EmzwM%22%2C%22%23primary%22%2C%22%23recovery%22%2C%22%23PiF0Sf3wDqec9_LYGO5T5-i4ihm7byhbUpoMq2nhZBg%22%5D%2C%22keyAgreement%22%3A%5B%7B%22id%22%3A%22%23keyAgreement%22%2C%22usage%22%3A%22signing%22%2C%22type%22%3A%22X25519KeyAgreementKey2019%22%2C%22publicKeyBase58%22%3A%2225aM2gBrRcZyK5GcGamw9QNH36D1mLxMn2GQ68twTSQr%22%2C%22controller%22%3A%22did%3Aelem%3AEiChaglAoJaBq7bGWp6bA5PAQKaOTzVHVXIlJqyQbljfmg%22%7D%5D%2C%22assertionMethod%22%3A%5B%22%23qfknmVDhMi3Uc190IHBRfBRqMgbEEBRzWOj1E9EmzwM%22%2C%22%23primary%22%2C%22%23recovery%22%2C%22%23PiF0Sf3wDqec9_LYGO5T5-i4ihm7byhbUpoMq2nhZBg%22%5D%2C%22id%22%3A%22did%3Aelem%3AEiChaglAoJaBq7bGWp6bA5PAQKaOTzVHVXIlJqyQbljfmg%22%7D&frame=%7B%7D&context=%7B%7D)

**Comment by gjgd** [comment]
See https://github.com/decentralized-identity/universal-resolver/issues/77#issuecomment-578528030 for a possible cause to the problem

**Comment by peacekeeper** [comment]
This should be fixed now, after I added the `https://www.w3.org/ns/did/v1` JSON-LD context to the [did-common-java library](https://github.com/decentralized-identity/did-common-java/tree/master/src/main/resources/did).

**Comment by peacekeeper** [comment]
We looked this on the [30 Jun 2021 Universal Resolver call](https://github.com/decentralized-identity/identifiers-discovery/blob/main/agenda.md#special-work-item-calls).

Closing, since this JSON-LD 1.1 problem was fixed long ago. Also see comment https://github.com/decentralized-identity/universal-resolver/issues/76#issuecomment-871600434.
