### ISSUE TITLE
JSON-LD Parsing Error Blocking VC Data Model Integration

### ISSUE THREAD

**Issue by OR13** [decentralized-identity/universal-resolver#77]
https://uniresolver.io/#did:btcr:xxcl-lzpq-q83a-0d5

https://raw.githubusercontent.com/OR13/self/master/ddo.jsonld

Per https://www.w3.org/TR/vc-data-model/#proofs-signatures-0

> If the cryptographic suite expects a proofPurpose property, it is expected to exist and be a valid value, such as assertionMethod.

However, `assertionMethod` is stripped from the btcr did document above by the universal resolver... this cause verification of credentials to fail when using the universal resolver as a document loader.

The solution is not to remove any of the properties defined in https://www.w3.org/ns/did/v1

**Comment by peacekeeper** [comment]
https://raw.githubusercontent.com/OR13/self/master/ddo.jsonld seems to have these `@context`s:

- https://w3id.org/security/v1
- https://w3id.org/did/v1

Neither of those define `assertionMethod`.

**Comment by OR13** [comment]
thanks, any chance we can surface this kind of issue to consumers? I'd rather not have properties silently dropped, it would be better to just day the document is not valid.

**Comment by OR13** [comment]
It would be wise for us to warn people relying on w3id.org for the did context to upgrade.

**Comment by OR13** [comment]
After updating to:

```
"@context": [
    "https://www.w3.org/ns/did/v1"
  ],
```

I now see an error. 

`Error: Request failed with status code 500: Resolve problem for did:btcr:xxcl-lzpq-q83a-0d5: Driver reported for did:btcr:xxcl-lzpq-q83a-0d5: invalid term definition: 1.1`

@gjgd is this the same issue you mentioned to me last week?

**Comment by OR13** [comment]
https://github.com/w3c/did-core/pull/156

**Comment by OR13** [comment]
back to being a universal resolver issue... [proof that my btcr did is valid jsonld](https://json-ld.org/playground/#startTab=tab-signed-rsa&json-ld=%7B%22%40context%22%3A%5B%7B%22%40version%22%3A1.1%7D%2C%22https%3A%2F%2Fwww.w3.org%2Fns%2Fdid%2Fv1%22%2C%22https%3A%2F%2Fidentity.foundation%2FOpenPgpSignature2019%2Fopenpgp-signature-2019-v0.0.0.jsonld%22%2C%22https%3A%2F%2Fdocs.element-did.com%2Fcontexts%2Fsidetree%2Fsidetree-v0.1.jsonld%22%2C%22https%3A%2F%2Fw3id.org%2Fsecurity%2Fv2%22%5D%2C%22publicKey%22%3A%5B%7B%22id%22%3A%22did%3Abtcr%3Axxcl-lzpq-q83a-0d5%23key-0%22%2C%22type%22%3A%22EcdsaSecp256k1VerificationKey2019%22%2C%22publicKeyHex%22%3A%2203195588392023a8a3af506660439d555971f0447b63616aa3c8272761310cf960%22%7D%2C%7B%22id%22%3A%22did%3Abtcr%3Axxcl-lzpq-q83a-0d5%23key-JUvpllMEYUZ2joO59UNui_XYDqxVqiFLLAJ8klWuPBw%22%2C%22type%22%3A%22EcdsaSecp256k1VerificationKey2019%22%2C%22publicKeyJwk%22%3A%7B%22crv%22%3A%22secp256k1%22%2C%22kid%22%3A%22JUvpllMEYUZ2joO59UNui_XYDqxVqiFLLAJ8klWuPBw%22%2C%22kty%22%3A%22EC%22%2C%22x%22%3A%22dWCvM4fTdeM0KmloF57zxtBPXTOythHPMm1HCLrdd3A%22%2C%22y%22%3A%2236uMVGM7hnw-N6GnjFcihWE3SkrhMLzzLCdPMXPEXlA%22%7D%7D%2C%7B%22type%22%3A%22OpenPgpVerificationKey2019%22%2C%22id%22%3A%22did%3Abtcr%3Axxcl-lzpq-q83a-0d5%23yubikey%22%2C%22controller%22%3A%22did%3Abtcr%3Axxcl-lzpq-q83a-0d5%22%2C%22publicKeyPgp%22%3A%22%5Cn-----BEGIN%20PGP%20PUBLIC%20KEY%20BLOCK-----%5CnComment%3A%20GPGTools%20-%20https%3A%2F%2Fgpgtools.org%5Cn%5CnmQENBF1N1CwBCADaCb%2FPSbxcxNf8baK6J2h1sKIAOX%2BYoq4yOx%2BbCvrzYXV5%2FNoz%5CnVCTaVvZUNQa745K6VSW%2FtQl9FtJ7zFi7D%2F5w8ZBAzdBeYkNWhWSZ6vTgUplAxtUp%5CnOnzijDIvEXDYk8Ab%2BCOSIPMXtDQOBPCYzxrqeHa%2BXHzMnfcM%2B6jNesOIN%2BRc%2B8O6%5CnsQAP%2ByZNmF3UopN9DolMiL%2BhvFlfqOYKFtn9bLg46%2Fb9SWCLdLv0NTmN3awAbkBX%5CngEY3jk5jiIrQ%2BKhkhFwQ3%2F7zo1tKfRjS1a3M5xL7m5O4iMqu24KJeQCbSuyVlGQG%5Cn42sPFOZxlyIqueqS9Rxzlma2qZjOHKsbFbBTABEBAAG0HkphbWVzIEJvbmQgPGph%5CnbWVzQGV4YW1wbGUuY29tPokBTgQTAQoAOBYhBOdlb45DbngEKt93B%2Bzq7eZsmT9w%5CnBQJdTdQsAhsDBQsJCAcDBRUKCQgLBRYCAwEAAh4BAheAAAoJEOzq7eZsmT9wXAAH%5Cn%2FRfl3o1Xj4i3KhJ5%2BjgP%2Fvi4ypHLQnk5lMWN%2FDz3xLy7apdaxGN5a76hdg2EQMHk%5CnaPXtPVFAdJs6RqDQkIls0s6%2Ft1sibo3UuTGIk6xmnYI8jyWkiQAmsA4IGkQ7Ch6E%5CnW3lqyHxbSBSJTRwmU8MUBUQyFrWLY9HMI7ThBquDf26zqJTsyyLWuM%2FdilPuFAHr%5Cnz6eBObWCmAcMuZfZByrHLp0dTckVIK9y%2FU9hfmF2El4P7ZNA2WILWJfBDzsIllyy%5CnhOQ%2BlxJQC4RJbn3Jd9CQCgiv%2BCuD3lb%2BLsdcFCsXGNrKm9ieiXLrqHm7rKXZ4Nbc%5Cn%2FBf6Q03zK4MjtOJl%2BwYfife5AQ0EXU3ULAEIANTtNQfUpZbts98js1bQWHXadrc5%5CnsI8n075U%2FKZ7b7zeAwoK%2FY28M%2BcuasyGWxQHK4SAtTjeopkZnoqZZCL6yIyJ6xHa%5CnPR5%2F54gtIFoGnWUoLLejb33AZIrV96g%2BvOh0ILTc2VXNAcGAS6zyEJ3qA98UcZ2g%5CnHnBmlih8bWZL79wfRITcCkHJNeHiwJ0E6u3%2B8rieIbKv3nqesWG7yafL4HlN%2F%2FIo%5CnHluiK29AbAqQy3tZ5NLKUDB1WG0xY7AwlkjwIjxl1tGbApFqet%2Bc5eTXN6ZnKCWK%5CnWbvu8bXkvOKiyJZcQmRLQzsV39iGiV822AdkQAf8ozfdMKtZ7Z3WThT1jWMAEQEA%5CnAYkBNgQYAQoAIBYhBOdlb45DbngEKt93B%2Bzq7eZsmT9wBQJdTdQsAhsgAAoJEOzq%5Cn7eZsmT9w4iIIAJDCm6nychT4YL2MvSX0z%2FNEdXuC1Y2n%2FlOHWcPNWIYJyWCcv3ID%5CnjGU76UX%2F6Tp4kfqLS3FTtJrQgemszZZ9lp09gE%2Fv4dgRu%2BkKwavGTwQPEV2kUjkq%5Cnyg5SO1ZZCdf%2B6OQwrI83PehDGtI78lXH4iN9IGPcELYpvwCcube%2BYDU4MpVFEDv%2F%5Cn0aGXt2htIeiKVtcG%2F2H2oD%2BiBr1MNxyaIfcmLuoOqlzCrPYL%2Bzyg5aynDV5Sq%2FB%2B%5CnJpR2gDSWJfAkeuhxKM9LatMdOTV6TZtqIRC2A9%2BVN0LQ%2BYnYVTYLm%2BdDOigzuBMT%5CnQeyzZfivXcZs8%2F7PiNAEVE3WyO8wHlIp5wy5AQ0EXU3ULAEIAKquC4FuHlBzfvlX%5CnHB8mpPLhh2G%2FtdH5TGnz01gKgYsiqoixvxOzIsNBWv%2FfPYHpzPGZVl3soNWM83Kt%5Cn%2Fgd7mwwaiXXAwvu42526W8pOjReU%2BGJaH%2Fot1DKijKqcAQhRZreYtFdAt3On%2FwdK%5CncGQ37nWVtOlpqFe2P27Oqi4bkDQPNQi6rCu5bnDXFzByfLLsIzERlHtuBpIn%2FxOE%5Cn0cBw9hNfcLox2Xz5IoQ1XQq9MXJKb4krLrQV4OHXHU%2BqeAHJ4dQTk0mf23%2FTMCBL%5CnAylbPwF5EO96uL9lKcEP3snKfC8ZlaAucadJ4eShcsLeV%2FeSHcwbnCDKFXGjiKP5%5Cn9974ZJsAEQEAAYkBNgQYAQoAIBYhBOdlb45DbngEKt93B%2Bzq7eZsmT9wBQJdTdQs%5CnAhsMAAoJEOzq7eZsmT9wW9sH%2Fj89m%2FTjr1KeTIR%2BxN9M0kHOtwmdMGkSNWeb3Vfc%5CnXEPZnz2CwLgO38RJY89MXk3umw8Z5ILW1SsAEoFG4%2F2mE1LilI5wk2jJcrU8%2BG05%5CnxCy9dN1AzK9GHc4mPgus01Na2ED1FzY4YgpJOxVCIqooXVtTfRoDkU39wH8Iyx9H%5CnGuxBmAJZB%2BOP1ve0Y3pqyoqpbgiI03x5dZBYlvQkSfGlVrd1hArtX%2Bdx3RqNbNHb%5CnHxA51vBHNSMFKQeBWENAbi0iKwFNaP1wFgzKzqzCJlv%2B%2FkxNMTZougTVUCzJFd7D%5CnBymBkVhDqSgww9qXiOvc6A%2FQ8w%2FGvbqKpV9VDRkF5CfalSKZAQ0EXU3ZeQEIANUD%5CnEEiQphKRIKkZJq1cYGbNu5Qm9nfNasnLrGCumOOuSQKqXajNdhjBSsiyMGN4WiHe%5CnIuZ9Ns%2Bry02vd9gb7VcSA7GvqQOrFqhHKnRj7bWPCSJiVTaIL0T52d%2BRESM0x%2BVB%5Cniv4iQ8ttJrDLb2LWH2ImAfYYesAIJP2lmi9Xws2lrFTPavvKW7oncj%2FV7GmW1yYm%5CnIb7%2FEZldyUz1FL4SkTVk2liFT5cKqsPqI%2F64sciDBzTm7%2Fy7f%2BMMlby4hUn7I%2FqL%5Cn%2FFTWSz1NMChMM8WhR3fru3DS0ETmYCjQP2Cl%2FByFdTwU9rbFP8R6lcF9zSSg4y1F%5CnnWEs%2BSWurm71TMl7jyMAEQEAAbQZSmFtZXMgPGphbWVzQGV4YW1wbGUuY29tPokB%5CnTgQTAQoAOBYhBPG9EvcSBvqh8jaZfWAELYdsMmFmBQJdTdl5AhsDBQsJCAcDBRUK%5CnCQgLBRYCAwEAAh4BAheAAAoJEGAELYdsMmFmw1AH%2F0pSrIl7fGGWF4duS0kNOpHR%5Cns74dLGBjdozi%2F2b2Bo6%2F3iHiH6uvpYUmzSjpzpP4dVE9zcIilFJjDTo62YFAsVky%5CngeAr1aHJPffNgTpuLJsE%2FDBeBsK2%2BBTMeXpEFPB1W6TWMC5RSAYDPiMMHgCtdiKy%5CnIxbKZ3AGYe0oHD9CWi88bDxA%2FC7pYKv3ZZHeMlY3vxsk7%2BJ96l6nZMCRolCEa1ay%5Cn0RoxulXLnh6XWpXXnghknO1sBJVzrEaIaU1HTiKV4Q%2FHzngmOSw%2BG1g45aZxHWDF%5CnTYXa4Rb0%2ByOzAdq9gVaeZnwKhNcezumGyk3OuiinBVRcrsfi0dIitb9scG4PLwS5%5CnAQ0EXU3ZeQEIAL8Ades4FDaaReuW5nXuYxoJ8qRzf6KpIsuvHK%2FKQL4ZMSg71HZQ%5CnKxoWWdcO3VPvdkFlBwp%2BKdY6g4S3ztzv9KiWt341WJdT%2B780RFix1jzyzqAVZinG%5CnCcPIcb%2Bc45QBkErUyQgcWvRae9AwZ8yavJlWatqyIJjm7tjg4GgnmbVN%2Fx1kbncq%5CnPyrC5ac61yg1gh5cLkdgYU2kSHLmKM1vUf%2BSlRNxrx2BGsICzXVzr1hjK7UBTxH3%5Cn0XzN6N0iHlIFt5uo8BZlg0TAvqoZr8Ra5P5VbS24pGBIpHmApQBtzFctDlzoZnoN%5CnSU9kVfuqpzCfxSr%2FnHdPeK5snYuKQOlhAj8AEQEAAYkBNgQYAQoAIBYhBPG9EvcS%5CnBvqh8jaZfWAELYdsMmFmBQJdTdl5AhsgAAoJEGAELYdsMmFmfJwH%2F3tftfzQ7gcj%5Cne%2F3HI4uJMPVBSyJyXE1zxCHS8pK8t7LzX8%2F8kfjig9GA%2BiLfiZqnZ%2BBfqMMpWGNb%5Cnz6yf1W5YfAlIEl0FaVbv%2BqPWVafy7L9pc3clQNWOrfVbBcl7wsiAb95MEaw9PR8t%5CnTifgllXeeHw1vMUm51wzs4WsPym60QgU4amhF7ESUW48ljUDSJGmmTV%2BVp%2F4xtTB%5CnasHrdcR34ARwrqCyvpLR5BUi2sVwcv3a2sE5XoOZZ%2BpTIah9KdPv4mcBvtZpC2V7%5CnV5x0lGufMz2W%2BfAJkv8Zq%2FWNhFkNmd4bNyEwV0Zl0dzEAW1PHqg9oqcoQgOPxPlf%5Cnc4sSEJZS20y5AQ0EXU3ZeQEIAKQV2xznTXSMPyJxNNY5BJXJYseMPwNhb6Vg9ZKi%5CnjUaOhgVtG7FzIEH9%2FhdBvay6%2FWe6%2BVXiZKQOBysZ2JMplNIxRbcccLGYLGXZAmO8%5CnnBq%2F67ebS%2FHyW1w9QlmW0TBj%2BK5R7RSApompmaUHoW0MTBoQN0EUqWg%2BAf86GnUw%5Cnu2IbfRHJfMsFd5LZ%2BHpWwVtgnQCliwSctn5KKx0doxHmxtvJzBw9K%2F0TqsThvkpm%5CnxcppVvJULAqc1mH%2BB4bk7Yv7Rnic74d4FW0HxBSMnuIVPSoVZTWxiFQh54z034A1%5CnK96nqa4R%2Fvvvpq7K%2FztNRCbDarpaugbk0E6wdYhMYMjpEysAEQEAAYkBNgQYAQoA%5CnIBYhBPG9EvcSBvqh8jaZfWAELYdsMmFmBQJdTdl5AhsMAAoJEGAELYdsMmFmZoIH%5Cn%2F2vV0j%2Bi2abVf52EjleGQUh1ii2jWTho%2Bg4qY22wZy7vwcwgLG%2FJQ859R4X%2FXWMk%5Cn3c8%2FjyA0hgmJIosoMC%2B%2B2m7DTPEw561ANrndTpRnzexin54lgzkHG6Kr%2BWmsNH6m%5CnXiS9ddXPaiUq%2BfkmjUW%2BVvAZ0G00M7S66u65dPD9m38ZPfFO9TKavQ9yXe%2FbHHNM%5CnqIyM2ecMX83Hhqd9wiUdb31JvABjwrZU0CSazK0LmtHP1DJPl0SM%2F4draIGkh%2Fnu%5CnlNbUCb9DRuOpOcFTzfDBNwI00ZWIMlb%2Fcz6LSvdk8t%2FPZZ19QrOXPyQi9YpTJDka%5CnrnFu2qXfCsLkrR23CVvbYS8%3D%5Cn%3Dq3UE%5Cn-----END%20PGP%20PUBLIC%20KEY%20BLOCK-----%22%7D%5D%2C%22authentication%22%3A%5B%7B%22type%22%3A%22EcdsaSecp256k1SignatureAuthentication2019%22%2C%22publicKey%22%3A%22did%3Abtcr%3Axxcl-lzpq-q83a-0d5%23key-0%22%7D%5D%2C%22assertionMethod%22%3A%5B%22did%3Abtcr%3Axxcl-lzpq-q83a-0d5%23key-JUvpllMEYUZ2joO59UNui_XYDqxVqiFLLAJ8klWuPBw%22%5D%7D)


not that I have to add 2 contexts to get it to be...

**Comment by gjgd** [comment]
Probably related to this error: https://github.com/jsonld-java/jsonld-java/issues/219

The probably looks like it is "@version": 1.1 being a number, but the jsonld-java lib only understands strings

**Comment by OR13** [comment]
Also related: https://github.com/decentralized-identity/context/issues/3

**Comment by troyronda** [comment]
We also encountered this issue when adding a second context with `@version: 1.1`. I am guessing the universal resolver doesn't fully support JSON-LD 1.1.

**Comment by JaceHensley** [comment]
Ran into this while using this context: `"https://w3id.org/security/v2"` since it has `"version": 1.1`. Maybe it should use https://github.com/filip26/titanium-json-ld instead since that supports json-ld 1.1?

**Comment by peacekeeper** [comment]
We looked at this on the [30 Jun 2021 Universal Resolver call](https://github.com/decentralized-identity/identifiers-discovery/blob/main/agenda.md#special-work-item-calls) and believe this can be closed, since the Universal Resolver should have full support for JSON-LD 1.1 by now. Also see comment https://github.com/decentralized-identity/universal-resolver/issues/76#issuecomment-871600434.

There is still an interesting question if unknown properties should be dropped, or if a warning or an error should be thrown, or if the Universal Resolver should not validate/modify DID documents at all. This should be discussed in a new issue.
