### ISSUE TITLE
Resolving DIDs to a specific ledger

### ISSUE THREAD

**Issue by swcurran** [decentralized-identity/universal-resolver#89]
In another issue, @peacekeeper wrote this:

> I don't think existing DIDs were migrated from the old testnet to the new testnet. Also, as far as I know, there is no way for a resolver to tell which network to use (it's not encoded in the DID itself).

Should DIDs or the DID method (or neither) provide a mechanism for a resolver to know which instance of a ledger (where there is one) to use?

I believe uPort had a mechanism, something like "did:uport:<net>:<id on net>" that enabled references to other networks using the same method -- a part of the DID Method. AFAIK every DID method has multiple ledgers to use - mainly test instances of the primary net. However, we've talked of multiple production instances that share a DID method. Should there be a mechanism to enable that at the DID or DID Method level?

I'm guessing this has been discussed before, so the answer may be just a pointer to the docs that I've not found.

Thanks

**Comment by OR13** [comment]
Yes, IMO we should be working to standardize this, with either resolver options or did name spacing, `did:example:dev:123`, `did:example:prod:123`, `did:example:customer1:123`

**Comment by cboscolo** [comment]
I strongly disagree with:
> Yes, IMO we should be working to standardize this, with either resolver options or did name spacing, did:example:dev:123, did:example:prod:123, did:example:customer1:123

It should be 100% up to the DID method to determine how to resolve test vs. production and how to craft everything to the right of `did:foo:` to accomplish this.

**Comment by peacekeeper** [comment]
I agree with @cboscolo on this.. Some methods use syntax like `did:sov:findy:1234` or `did:erc725:ropsten:1234`, while e.g. `did:btcr:` encodes the information "mainnet or testnet" in a different way. Also keep in mind that "ledger" or "network" or "testnet" etc. are all method-specific concepts, in my opinion it's not a good idea to assume these that concepts always exist in DID methods or that they have comparable meaning.

Methods should have complete freedom how they want to design everything to the right of the second `:`, as long as the method spec somehow defines how to get the DID document.

Related issue in the spec: https://github.com/w3c/did-core/issues/98

**Comment by swcurran** [comment]
Thanks all - and for the link @peacekeeper.  I'm happy with the answer and agree it's the right solution. I really just wanted to find out about any discussion that had been previously held on this.

I'm going to close this.

**Comment by peacekeeper** [comment]
Just in case, I created a PR for DID Core to clarify this: https://github.com/w3c/did-core/pull/215
