### ISSUE TITLE
Cannot resolve did:web

### ISSUE THREAD

**Issue by OR13** [decentralized-identity/universal-resolver#92]
Working:

https://uniresolver.io/1.0/identifiers/did:key:z6MksHh7qHWvybLg5QTPPdG2DgEjjduBDArV9EF9mRiRzMBN
https://uniresolver.io/1.0/identifiers/did:web:identity.foundation
https://identity.foundation/.well-known/did.json

Not Working:

https://uniresolver.io/1.0/identifiers/did:web:chapi.did.ai
https://chapi.did.ai/.well-known/did.json

Error:

`Resolve problem for did:web:chapi.did.ai: DID document missing context`

(not correct, bypassing the UR resolves the issue, and supports credential verification).

Is there an endpoint which does not process jsonld contexts yet? or a way to clear the cache of the resolver via http?

**Comment by peacekeeper** [comment]
Actually, in this case it seems to be not the fault of the Universal Resolver processing the JSON-LD contexts, but it seems to be an issue with the driver:

```
docker run -ti --rm -p 8081:8081 uport/uni-resolver-driver-did-uport:latest
```

```
curl -H "Accept: application/json" "http://localhost:8081/1.0/identifiers/did:web:chapi.did.ai"

DID document missing context
```

I imagine this is the underlying problem:
https://github.com/decentralized-identity/web-did-resolver/blob/develop/src/resolver.ts#L34

We should raise an issue there, and then ask to release a new version of the driver.

**Comment by OR13** [comment]
Thanks for tracing this, I have opened an issue here: https://github.com/decentralized-identity/web-did-resolver/issues/26

**Comment by peacekeeper** [comment]
This should work now after the fix has been applied (see https://github.com/decentralized-identity/web-did-resolver/pull/29), the driver has been rebuilt (see https://github.com/uport-project/uport-did-driver/issues/5), and the Universal Resolver config has been updated (see https://github.com/decentralized-identity/universal-resolver/commit/bae0b88b607b53c30e65de3abb8a157a5f20935a).

Try now: https://uniresolver.io/1.0/identifiers/did:web:chapi.did.ai
