### ISSUE TITLE
Failed to start docker image universalresolver/uni-resolver-web:latest

### ISSUE THREAD

**Issue by fqutishat** [decentralized-identity/universal-resolver#93]
uni-resolver-web_1               | Downloading from central: https://repo.maven.apache.org/maven2/decentralized-identity/did-common-java/0.1.0/did-common-java-0.1.0.jar
uni-resolver-web_1               | [INFO] ------------------------------------------------------------------------
uni-resolver-web_1               | [INFO] BUILD FAILURE
uni-resolver-web_1               | [INFO] ------------------------------------------------------------------------
uni-resolver-web_1               | [INFO] Total time:  13.685 s
uni-resolver-web_1               | [INFO] Finished at: 2020-03-16T14:33:16Z
uni-resolver-web_1               | [INFO] ------------------------------------------------------------------------
uni-resolver-web_1               | [ERROR] Failed to execute goal on project uni-resolver-web: Could not resolve dependencies for project decentralized-identity:uni-resolver-web:war:0.2-SNAPSHOT: Could not find artifact decentralized-identity:did-common-java:jar:0.1.0 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
uni-resolver-web_1               | [ERROR] 
uni-resolver-web_1               | [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
uni-resolver-web_1               | [ERROR] Re-run Maven using the -X switch to enable full debug logging.
uni-resolver-web_1               | [ERROR] 
uni-resolver-web_1               | [ERROR] For more information about the errors and possible solutions, please read the following articles:
uni-resolver-web_1               | [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by fqutishat** [comment]
@peacekeeper

**Comment by fqutishat** [comment]
Step to reproduce:
git clone https://github.com/decentralized-identity/universal-resolver
cd universal-resolver/
docker-compose -f docker-compose.yml pull
docker-compose -f docker-compose.yml up

**Comment by philpotisk** [comment]
We actually have changed the Maven depdendeny-management today, so that released libraries are used rather than libraries in development (SNAPSHOT versions). For accessing the Maven registry, a Personal Access Token for GitHub must be placed in the file resolver/java/settings.xml. This is also explained in this README https://github.com/decentralized-identity/universal-resolver/blob/master/resolver/java/README.md. As this is not obvious, we will consider to make this documentation more transparent. Thanks for pointing this out.

**Comment by fqutishat** [comment]
@philpotisk I thought we need these dependency when building the image not on starting?

**Comment by gjgd** [comment]
@philpotisk Could you indicate the minimal set of scopes needed when creating the personal access token?
<img width="793" alt="Screenshot 2020-03-17 at 01 18 16" src="https://user-images.githubusercontent.com/7913565/76778495-4b82e100-67ed-11ea-8f7b-73c5adb49b54.png">

**Comment by fqutishat** [comment]
@philpotisk  I think we need to add --settings /opt/uni-resolver-java/settings.xml  to https://github.com/decentralized-identity/universal-resolver/blob/master/resolver/java/uni-resolver-web/docker/run-uni-resolver-web.sh

**Comment by fqutishat** [comment]
mvn jetty:run should be mvn -settings /opt/uni-resolver-java/settings.xml jetty:run

**Comment by fqutishat** [comment]
@philpotisk we fix it in our repo https://github.com/trustbloc/trustbloc-did-method/pull/35/files

**Comment by philpotisk** [comment]
For the personal access token, only the scope **read:packages** is required.

Thanks a lot for spotting and fixing the issue related to the startup command. I have updated the code-base and the documentation accordingly.
