### ISSUE TITLE
uni-resolver-web build error

### ISSUE THREAD

**Issue by weichweich** [decentralized-identity/universal-resolver#94]
I'm not able to build the `uni-resolver-web` image using `docker build --no-cache -f ./resolver/java/uni-resolver-web/docker/Dockerfile . -t universalresolver/uni-resolver-web`.  When I try to build it I get the following error:

`
[ERROR] Failed to execute goal on project uni-resolver-core: Could not resolve dependencies for project decentralized-identity:uni-resolver-core:jar:0.2-SNAPSHOT: Failed to collect dependencies at decentralized-identity:did-common-java:jar:0.1.0: Failed to read artifact descriptor for decentralized-identity:did-common-java:jar:0.1.0: Could not transfer artifact decentralized-identity:did-common-java:pom:0.1.0 from/to github (https://maven.pkg.github.com/decentralized-identity/did-common-java): Transfer failed for https://maven.pkg.github.com/decentralized-identity/did-common-java/decentralized-identity/did-common-java/0.1.0/did-common-java-0.1.0.pom 400 Bad Request -> [Help 1]
`

I am up-to-date with the current master (48defa6529a65042a825599567378f7baaeaf6c6).

**Comment by philpotisk** [comment]
@weichweich Please place a Personal Access Token in file resolver/java/settings.xml, as stated in the Quick Start section here https://github.com/decentralized-identity/universal-resolver/blob/master/README.md

As a matter of fact, GitHub is not allowing the access of Maven-dependencies without such a token.

**Comment by weichweich** [comment]
Thanks for the fast answer! I didn't notice that. Building the image works with the token.
